### ISSUE TITLE
„unerwartete Ausgabe“-Warning on plugin activation

### ISSUE THREAD

**Issue by FlorianBrinkmann** [awsmug/torro-forms#112]
Hi!

I get the following warning after activating the plugin:
> Das Plugin verursachte eine Fehlermeldung 516 Zeichen unerwartete Ausgabe während der Aktivierung. Sollte du Fehlermeldungen wie „headers already sent“, Probleme mit der Syndizierung der Feeds oder andere Fehler erhalten, versuche das Plugin zu deaktivieren oder zu löschen.

My WordPress version is 4.4.2

**Comment by mahype** [comment]
Hello Florian,

which version do you have downloaded?

**Comment by FlorianBrinkmann** [comment]
Hi Sven,

I used the link from torro-forms.com (https://github.com/awsmug/torro-forms/archive/master.zip), so I think the latest?! :)

**Comment by mahype** [comment]
I'm sorry for the circumstances, but we are deep within to change the code for the API to finish the first version of Torro Forms. At the moment I would recommend to use this version:

https://github.com/awsmug/torro-forms/releases/tag/v1.0.0beta19

If you want to know more about what happens with the software in the next weeks, you also can get me as @mahype in Slack or as svenwagener79 at Skype. :)
