### ISSUE TITLE
Consider changing post type name

### ISSUE THREAD

**Issue by felixarntz** [awsmug/torro-forms#136]
* post type slugs should not contain hyphens
* post type slugs are commonly singular, but ours currently is plural

Therefore I would propose to change it from `torro-forms` to `torro_form`.

A pretty deep change, but for the most it's only search and replace. I think we can still do this before doing beta 1.0. @mahype what do you think?

**Comment by felixarntz** [comment]
The same would apply to the taxonomy (rename `torro-forms-categories` to `torro_form_category`).

**Comment by mahype** [comment]
I totally agree. Just start this job and take care about eventually reworking updarte scripts. Thank you!

**Comment by felixarntz** [comment]
Note that, of course, the update script needs to be run to migrate existing forms and categories. Deactivate and then reactivate the plugin to do so
