### ISSUE TITLE
Make installation multisite-compatible

### ISSUE THREAD

**Issue by felixarntz** [awsmug/torro-forms#137]
* currently the plugin only runs its installed/activated/deactivated routine on the current site even when network-activated

**Comment by mahype** [comment]
What would be your proposal, to handle the multisite activation?

**Comment by felixarntz** [comment]
What do you mean? we need to do the DB table version check (and possibly installation) and flush rewrite rules for all sites (in the network) instead of just the current site if the plugin is network activated. This is a fairly straightforward process
