### ISSUE TITLE
Call to undefined method Torro::form() 

### ISSUE THREAD

**Issue by staude** [awsmug/torro-forms#138]
HI,

i installed torro on an multisite and activetd it on one site. after insert the [form id=8] shortcode on an post, i have an fatal error.

Fatal error</b>:  Call to undefined method Torro::form() in <b>..../wp-content/plugins/torro-forms/core/shortcodes.php</b> on line <b>62</b><br />

i used the current master branch.

**Comment by felixarntz** [comment]
This is fixed. Note however that the plugin does not work properly yet if you network-activate it (see #137). Just something you might wanna know. Thanks for the bug report!
