### ISSUE TITLE
torro()->forms()->create() throws WP_Error

### ISSUE THREAD

**Issue by mahype** [awsmug/torro-forms#145]
On creating a form by using torro()->forms()->create() function. I will get the following error message:

"Content, title, and excerpt are empty.".

**Comment by felixarntz** [comment]
How exactly do you call this function?

**Comment by mahype** [comment]
I just call it in this way:

`$args = array(
		'title' => 'Testing superfunctions'
	);

$form = torro()->forms()->create( $args );
`
