### ISSUE TITLE
Adding arguments variable to replace_column_name & replace_column_value

### ISSUE THREAD

**Issue by mahype** [awsmug/torro-forms#174]
For different cases of getting values (e.g. getting an URL or a HTML link to an uploaded file), there need to be a argument parameter in functions.

**Comment by mahype** [comment]
@felixarntz 

We should think about to filter result columns and values in a better way. We filtered media values with HTML replacement. That's not fitting for Excel or CSV exports. My try to change this was an opener for a bigger change at all.

**Comment by felixarntz** [comment]
I fixed this while restructuring the result handlers which needed to use the new models and managers (see #150). An element class can now have a method `render_value( $value )` to create HTML output and an another method `render_value_for_export( $value )` that handles output Excel and CSV files. Both methods are optional though, if they do not exist, the unmodified value is used.
