### ISSUE TITLE
"Delete Element" Button placement

### ISSUE THREAD

**Issue by arkonisus** [awsmug/torro-forms#184]
The "Delete Element" Button at the bottom of each form element should be either placed at a different location or styled in a different way. 

![delete](https://cloud.githubusercontent.com/assets/7242966/14934636/88dabf98-0eb7-11e6-828b-889f766b5b47.png)

A button after a list of options will be noticed as a "confirm" element much more as a "delete" element.

**Comment by mahype** [comment]
Thank you for your help! :+1:
