### ISSUE TITLE
split `Torro_Element` into two classes

### ISSUE THREAD

**Issue by felixarntz** [awsmug/torro-forms#188]
There should actually be a class `Torro_Element_Type`. All element types should be derived from that class. The current `Torro_Element` serves two purposes and is not consistent there.

This might produce problems in the future. I really hope we can get this into the first beta because otherwise there's no way we can change that any longer.

But this should be the last task to do, the rest has higher priority.

**Comment by felixarntz** [comment]
I'll work on this in a separate branch. This is a heavy change, so I'll try to work it out. If we can't get it ready for the beta, let's skip it.

**Comment by mahype** [comment]
Is this really a bug?
