### ISSUE TITLE
Keine Fehlermeldung bei Einbindung mit Shortcode

### ISSUE THREAD

**Issue by Soean** [awsmug/torro-forms#200]
Ich habe ein Formular mit required* Feldern erstellt.

Wenn ich das Formular über den Post Type direkt aufrufe /forms/formularname/ wird bei nicht ausgefüllten Feldern eine Fehlermeldung angezeigt "You must input something.". 
Wenn ich das Formular per Shortcode einbinde, wird nach Absenden keine Fehlermeldung angezeigt.

**Comment by mahype** [comment]
Danke Dir! Ich check das mal!
