### ISSUE TITLE
Warning: ucwords() expects exactly 1 parameter

### ISSUE THREAD

**Issue by websupporter** [awsmug/torro-forms#205]
Hi!
Playing a bit around with your great plugin. Did run into this:

>Warning: ucwords() expects exactly 1 parameter, 2 given in /var/www/html/multisite/wp-content/plugins/torro-forms-master/core/managers/class-manager.php on line 78

```
if ( empty( $class->description ) ) {
			$class->description = sprintf( __( 'This is a %s module.', 'torro-forms' ), ucwords( $class_name, '_' ) );
		}

```

Not quite sure, what you try to do here. My fix was just 
`$class->description = sprintf( __( 'This is a %s module.', 'torro-forms' ), ucwords( $class_name ) );`

But there is a reason for the underscore I guess.

**Comment by websupporter** [comment]
Strange.http://php.net/manual/en/function.ucwords.php accepts a second parameter. I run 5.5.9, should work just fine. I will dig a bit deeper... Sorry.

**Comment by websupporter** [comment]
Ha. Added in 5.5.16 > 5.5.9 right? :/

**Comment by mahype** [comment]
The Plugin should work on PHP 5.2 because of the minimal requirements of WordPress. So I will check this. Thank you!

**Comment by mahype** [comment]
I have added a fix for that. So it's fixed now in the develop branch.
