### ISSUE TITLE
Implement Captcha-free honeypot

### ISSUE THREAD

**Issue by tyrann0us** [awsmug/torro-forms#206]
Hi,
do you mind adding a captcha free honeypot solution (like https://github.com/nocean/cf7-honeypot does for Contact Form 7)?

We have a lot of customers who don't like captchas or even don't understand how to use it.

Thanks!

**Comment by mahype** [comment]
Yes we will do that! I'll check when we can do that ang will give you feedback.

**Comment by mahype** [comment]
Further discussions will be made in Issue #260
