### ISSUE TITLE
reCAPTCHA is not performing

### ISSUE THREAD

**Issue by mahype** [awsmug/torro-forms#225]
Hi @felixarntz,

do you have an idea why the reCAPTCHA is not working here?

https://wordpress.org/support/topic/recaptcha-not-working-15

I could not reproduce the error.

Thaaaaank you! :)

**Comment by felixarntz** [comment]
I cannot reproduce it either... I responded in the support thread to ask for further details. If we don't get a response by tomorrow, we need to punt this to beta 7.

**Comment by felixarntz** [comment]
Closing since no response from reporter
