### ISSUE TITLE
Option to save results after every submit

### ISSUE THREAD

**Issue by mahype** [awsmug/torro-forms#236]
For different reasons there could be a possibility to save the form data after every page submit.

Example:
https://wordpress.org/support/plugin/torro-forms

**Comment by dc8johnson** [comment]
Do you have plans for how this would be implemented, a description of the feature? I have some interest in the ability to complete a survey over multiple sessions. This would require the ability the save the survey with each submit and the ability for a user to pick up where they left off.

**Comment by felixarntz** [comment]
Done as part of refactoring.
