### ISSUE TITLE
E-Mail Benachrichtigung: Formular Felder nicht auswählbar

### ISSUE THREAD

**Issue by Soean** [awsmug/torro-forms#237]
Wenn ich eine neue E-Mail Benachrichtigung erstelle und ich rechts auf das "+" klicke, um ein Feld-Platzhalter auszuwählen, werden mir die Formularfelder nicht angezeigt.

Wenn man eine E-Mail Benachrichtigung erstellt, die Seite neu lädt, sind die Felder auswählbar.

**Comment by mahype** [comment]
Ja das ist derzeit noch so, da die Felder leider noch nicht zur Laufzeit hinzugefügt wird. Man muss dummerweise nochmal speichern. Das muss allerdings noch behoben werden.

**Comment by felixarntz** [comment]
This now works correctly in JavaScript as well in the refactored version (via 8b0cc35064d907e8016407f944991b069219681f and 3724a99ea9e9654818f5e67ffad7b23bce7d9dfb).
