### ISSUE TITLE
Exclude content field from email notification form field selector

### ISSUE THREAD

**Issue by tyrann0us** [awsmug/torro-forms#238]
I just started to play with this good looking plugin. There are a couple of things I noticed while working with it which I would like to split up in separate issues.

I my opinion there's no need for the content field to be selectable in the email notification form field selector.

Here's why: The content field can only be used to display content to the user, so why should someone add it as a email template field? Additionally if the field contains long paragraph it makes the selector to become very long and inefficient to use.

![image](https://cloud.githubusercontent.com/assets/8144115/16546609/19e91a32-4150-11e6-8142-774de971a6ba.png)
An unnecessarily (long) form field.

**Comment by mahype** [comment]
OK! That's right! I only allow templatetags from those elements which have an input and where the label is set. I have fixed it and you can test it from the develop branch.

Thank you for helping again! :)
