### ISSUE TITLE
Undefined index: label in /core/element-types/base-element-types/content.php on line 67

### ISSUE THREAD

**Issue by tyrann0us** [awsmug/torro-forms#240]
WordPress: 4.5.3
Torro Forms 1.0.0-beta.6
PHP: 7.0.7 (FastCGI)

Since beta-6 I'm getting this error `Notice: Undefined index: label in /var/www/vhosts/example.com/httpdocs/wp-content/plugins/torro-forms/core/element-types/base-element-types/content.php on line 67`.

This is the method `to_json()` in class `Torro_Element_Type_Content` which was added in beta-6.

**Comment by mahype** [comment]
Thank you for reporting! It's fixed now. :) Please use the develop branch to test if it works for you.
