### ISSUE TITLE
Only load frontend scripts if forms are used

### ISSUE THREAD

**Issue by mahype** [awsmug/torro-forms#241]
"Das Problem, was ich habe, ist, dass das Plugin immer 3 CSS Dateien und 2-3 JS Dateien auf die Seite packt, egal ob ein Formular auf der jeweiligen Seite ist oder nicht.".

**Comment by felixarntz** [comment]
Da müsste man ja einfach prüfen ob der Form Controller im Moment nen Formular erkannt hat oder nicht.

**Comment by mahype** [comment]
Also ich musste schon noch was machen. Ich habe jetzt die Funktionen zur Formdetection nochmal überarbeitet und Funktionen zur Chartdetection eingebaut. Bei mir hat das bisher soweit funktioniert und die Skripte wurden geladen wo sie geladen werden mussten.

**Comment by mahype** [comment]
Es wird dann jetzt also differenziert zwischen Formular-Skripten und Chart Skripten. Die werden jetzt genau dann geladen, wenn sie geladen werden müssen.
