### ISSUE TITLE
Results not sent if multiple pages are set. 

### ISSUE THREAD

**Issue by hutsori** [awsmug/torro-forms#246]
When multiple pages are set, only the last page's results are sent to email notification. 

You can still see all the results in the result page. It just doesn't email you the first page's results.

**Comment by mahype** [comment]
I have added a fix for that. Sending results should work again.

Can you please test it with the develop branch? Thaaaaank you! :)

**Comment by hutsori** [comment]
All results are now showing in the email.  But following bugs are appeared:

1. When email is sent, some results are in one single line: 
You put {allelements} in the results email action, it seems like it's working but if you set individual question element, you'll get all the answers in one single line. They don't change paragraph. 

2. If you export the data to excel, multiple choice questions only output yes or no instead of your answers. For example if you have a 3-choice multiple question, and say you chose answer 2, you'll have 1 - no, 2 -yes, 3 - no in your excel file.

**Comment by mahype** [comment]
Hello Min,

I have fixed point 1.  There was no wpautop on the message of the email notifcation.

For point 2. this is right. We just output if the user have checked the checkbox which you can see in the table header or not. That is no bug. If you have recommendations how to display it in another way, just let me know. 

Greetings,

Sven

**Comment by hutsori** [comment]
Sven,

You actually have a point on #2. I think it's not really a bug after all. However, can you change the multiple choice outputs to commas instead of ul,li tag's black dot in the email? The reason is that the black dot (ul li tag) gives you somewhat awkward looking result. Because it's a list, the result text isn't aligned along with the rest of the results. 

So, say you answered A,B,C for your multiple choice question, then you would have the result email:
  • A
  • B
  • C

But instead, I think it's better to have just:
A,B,C

Just a thought.  :)

**Comment by mahype** [comment]
Hi Min,

yes it's a good idea to change it at this place. But I would also add a Filter, where everybody can change the value and change it to their needs.

But we have to discuss that in an additional ticket. 

Greetings,

Sven

**Comment by mahype** [comment]
Take a look at Ticket #248

**Comment by mahype** [comment]
@hutsori I have changed the templatetags appearance on array values from UL to comma separated values.

See Ticket #248
