### ISSUE TITLE
Change Results entry order?

### ISSUE THREAD

**Issue by hutsori** [awsmug/torro-forms#247]
Hello Sven, 

If I were to check the very recent result in the admin page, I'd have to click next button if there are many entries because the newest entry is at the very last page of the entries tab. 

It gets annoying if I have many many results because you'd have to click the next button many times. Is it possible to change the entry order from oldest -> newest , to newest -> oldest?

**Comment by mahype** [comment]
Yes thats a good point. I will change that. Sorting the results dynamical will be done at a later point.

**Comment by hutsori** [comment]
Did you change anything? I get the entries from newest to oldest now. And so are the results inside. 
Now everything is backward: I see the last question first and first question last and it happens in the excel export too. Could you take a look at this?

**Comment by mahype** [comment]
Thats crazy! That should not be. I don't have changed anything here yet. So I definetly have to take a look at it ;)
