### ISSUE TITLE
script loading error. 

### ISSUE THREAD

**Issue by hutsori** [awsmug/torro-forms#250]
Sven, 

I occasionally get script related error in the admin page. 

results-charts-c3.min.js?ver=4.5.3:5 Uncaught TypeError: n.data(...).split is not a function

[screen shot](http://i.imgur.com/OHxwzDV.png)

When this error occurs, you can't open up your element. Unfortunately, I don't know how to reproduce it. It just happens and once it happens, you just have to delete this form.  

Your account to my site is still open. Please take a look. I have created 2 forms: pop and ioi. 
pop works fine but ioi has this error. 

Thanks.

**Comment by mahype** [comment]
Thank you! I will take a look at it.

**Comment by hutsori** [comment]
Ok. I still don't know how to reproduce it, but I know this happens when answers are submitted. 
The error is gone if you delete all the results.

**Comment by hutsori** [comment]
Ok. The error occurs when: 
1. If you have the exact same answers for your question. 
2. If you have only one answer for your question.
3. You answer to these questions. 

This usually won't happen to many people. No one would put the same answers for their questions. But as for #2, this might be a problem because single answer questions can also be used as an agreement on terms and condition.  

For example:
Q: Please check if you have read the terms and condition. 
[] Yes, I have read the terms and condition and I agree. 

What do you think?

**Comment by mahype** [comment]
Hello Min,

I have fixed this now! This JS issue was, because on one answer JS just had a number and didn't recognized it as a string and so there was no .split function. I have forced it now to handle it as a string.

Greetings,

Sven

**Comment by hutsori** [comment]
Great!
