### ISSUE TITLE
Ability to delete single result from database?

### ISSUE THREAD

**Issue by hutsori** [awsmug/torro-forms#251]
Sven, 

I just realized once data is inserted, you can either delete the whole database, or cannot do nothing. What if you wanted to add a new question to your existing questions? You would definitely want to test it out before releasing it to the public but if you test it, you would end up messing up your existing data.  

Could this feature be added? Just a thought.

**Comment by mahype** [comment]
Yes this is a good idea! I will add this to our list.

**Comment by hutsori** [comment]
Hi Sven, 
Any progress on this? I don't know why but I just got an empty first page result somehow (all data from the first page is empty but not the second page) and this is affecting my whole data base. Since I do not know how this error happened nor how to reproduce it, I just want to delete it, so at least it won't affect my data base. Really appreciate all your work!

**Comment by felixarntz** [comment]
Granular control over form submissions will be available in the refactored version (see #348).
