### ISSUE TITLE
Notification text area not not loaded as rich text editor

### ISSUE THREAD

**Issue by zottto** [awsmug/torro-forms#252]
If I create a new form and add some elements to it and than head over to the notification section (without saving / reloading the page) to add a new notification there, the message field of the notification is a simple textarea and no rich text editor. Adding fields to this textarea is not possible.
No JS error in the debug console.

**Comment by mahype** [comment]
Thats crazy. I cannot reproduce it anymore after some changes. Do you can confirm that the issue is gone?

**Comment by zottto** [comment]
I can still reproduce it with the latest developer version of the plugin.

**Comment by felixarntz** [comment]
This is no longer an issue in the refactored version.
