### ISSUE TITLE
Excel import?

### ISSUE THREAD

**Issue by hutsori** [awsmug/torro-forms#254]
Sven, 

A thought has crossed my mind. What if my server crashes? or if I wanted to change my server? 
If so, I'd loss all data. Torro form currently supports export only. But it would be great if you can import data as well. What do you think?

**Comment by mahype** [comment]
Hi Min,

yes we have also thought about it. But only to import forms, not the results. See here:

https://github.com/awsmug/torro-forms/issues/73

If you want to save your results you should backup your Database.

Thank you for your recommendation!

Greetings,

Sven
