### ISSUE TITLE
Possibility to add CSS (or other extra data) to a field

### ISSUE THREAD

**Issue by zottto** [awsmug/torro-forms#255]
Sometimes it is needed to add some extra css class to one of the fields or to add some data attributes. This is not possible at the moment.
Example: to build your own honey pot solution, you want to add a special class to one text field to hide this field via css.
Even easier: you just want to highlicht one of the fields as important.

**Comment by felixarntz** [comment]
We might add this at a future date, but generally our aim is to keep the UI of the plugin simple.

What you can currently do is to use the filter `torro_element_classes`, for example like this:

```php
function add_my_class( $classes, $element ) {
    if ( 'This field should be hidden' == $element->label ) {
        $classes[] = 'hide-this-field-class';
    }
    return $classes;
}
add_filter( 'torro_element_classes', 'add_my_class', 10, 2 );
```

**Comment by zottto** [comment]
That's ok for me, but possibly there will be other users that do not want to add some code only to add a CSS class. ;-)

**Comment by LeisureLarry** [comment]
We had this discussion with Sven at WordPress Meetup Nuremberg a few days ago. Classes are for designers and should be a setting without the need to code.

**Comment by mahype** [comment]
Field is added in settings tab to all elements
