### ISSUE TITLE
Allow individual name attribute

### ISSUE THREAD

**Issue by zottto** [awsmug/torro-forms#256]
Attributes of fields are generated automatically.
Sometimes it is helpful to have the possibility to define some attribute values on your own.
Example: Recreate a Mailchimp newsletter signup form, which need special name attributes to be recognized by Mailchimp.

**Comment by felixarntz** [comment]
The name attributes are currently required to follow a certain structure to be compliant with Torro Forms functionality. We are working on an API to map form fields to certain data which can then be fetched to access a service like Mailchimp.
Manually changing the field names is unfortunately nothing we can do at this point.

**Comment by zottto** [comment]
Would be great to have a possibility to replace all the other pseudo-form builder (like Mailchimp plugin) with TorroForms.
For a replacement of the Mailchimp plugin it is also needed to have an individual action defined.

It's ok for me to do that with an API call, although I think that not so advanced users would like to be able to do that stuff in the GUI.

**Comment by mahype** [comment]
I think about to add filters for that cases that you can filter element names, ids or form actions. If users like to change that, they should know that the form processing wont work anymore and they have to handle it by their own.

**Comment by mahype** [comment]
But as @felixarntz says, we are going to prepare additional plugins for a real API connection to such services.
