### ISSUE TITLE
Feature request: Anonymized IPs

### ISSUE THREAD

**Issue by LeisureLarry** [awsmug/torro-forms#258]
Asking Sven at WordPress Meetup Nuremberg a few days ago, he told us that IPs are not hashed or anonymized. It would be great to have a setting which hashes the IPs with MD5 and then strips the beginning and closing characters to anonymize it.

**Comment by tyrann0us** [comment]
Probably not by default but settings based.

**Comment by LeisureLarry** [comment]
Yes, should be a setting, as anonymized IPs are not a 100% proof for a duplicate.

**Comment by felixarntz** [comment]
Done in the refactor (see #348).
