### ISSUE TITLE
Feature request: Notification eMails Reply-to

### ISSUE THREAD

**Issue by LeisureLarry** [awsmug/torro-forms#259]
Sven showed us the notification settings in the backend at WordPress Meetup Nuremberg. Currently the person which is filling the form can be set as sender. GMX, web.de and many others changed their spam detection this year. This settings doesn't make sense any longer. Instead a setting is needed to set this person's mail as reply-to in the additional mail headers.

http://contactform7.com/best-practice-to-set-up-mail/
https://www.internetkurse-koeln.de/contact-form-7-validierung-meldet-konfigurationsfehler/

**Comment by mahype** [comment]
I have added the field now. Please install the latest develop version of the plugin and switch the plugin off and on.

Thank you for your recommendation! :)
