### ISSUE TITLE
Feature request: Change position of form elements selection in backend

### ISSUE THREAD

**Issue by LeisureLarry** [awsmug/torro-forms#261]
The selection is currently above the box with the save button. But WordPress default is to have this box as first box in the right sidebar. Better put the selection as default in the left column above the box for the multipage forms. Form elements might be 250px wide buttons there.

**Comment by mahype** [comment]
I will talk about it with @felixarntz. But one thing we discussed is, to change the CSS that you can put the elements on the top or at the botton of the main columnt where the content is also.

**Comment by LeisureLarry** [comment]
Yes, there should be CSS for left and right column. I think it would be best to position it in the left column as default. With tendency to rise each form element below each other would become a very long list.

**Comment by mahype** [comment]
Elements are now responsive and if you put them under the Editor they will be wrapped for a better view.
