### ISSUE TITLE
Feature: possibility to add text for placeholder attribute

### ISSUE THREAD

**Issue by zottto** [awsmug/torro-forms#266]
Please add a possibility to add additional placeholder text for input fields.

Thanks!

**Comment by mahype** [comment]
Just added! You can change it in the settings tab or by filter 'torro_input_placeholder'.

**Comment by Soean** [comment]
PHP Notices:

Notice: Undefined variable: element_id in .../torro-forms/core/element-types/base-element-types/textfield.php on line 65 

Notice: Undefined variable: element_id in .../torro-forms/core/element-types/base-element-types/textarea.php on line 58
