### ISSUE TITLE
showing percentage on top of bar graph.

### ISSUE THREAD

**Issue by hutsori** [awsmug/torro-forms#267]
Sven, 

Can the bar chart show percentage on top of each bar? 
<img src="http://i.imgur.com/Nh05dag.png" />
Also, it'd be better if it shows the total number of participant at the bottom of the graph. 

It would be then so much easier to analyze the data.

**Comment by mahype** [comment]
Thank you Min! :)

**Comment by felixarntz** [comment]
The refactored version now contains an option to show labels with each data point, either the absolute value or a percentage.
