### ISSUE TITLE
Spin off the results section from the form builder into its own submenu item 

### ISSUE THREAD

**Issue by rpkoller** [awsmug/torro-forms#272]
We've talked about that at the WPMeetup in Nürnberg. At the moment a form contains all the used fields, actions, results and general settings. My point was that contextually it would be the cleaner approach to spin off the results section for the forms into their own submenu item. Inside the `All forms`submenu item you have the settings for each created form while inside the to be created `Results`submenu item you would have the according results. That way would be able to grant different access levels and make the results available to more user groups in contrast to the form settings only available to the admin user for example. You could give visual feedback in the sidebar showing updates in the results section. And overall it would be a cleaner more intuitive cleaned up user experience.

**Comment by felixarntz** [comment]
Form submissions will have their own admin area and be able to be granularly controlled in the refactored version (see #348).
