### ISSUE TITLE
Namespace and unify the torro forms shortcodes

### ISSUE THREAD

**Issue by rpkoller** [awsmug/torro-forms#273]
We've talked about that at the WPMeetup in Nürnberg. At the moment you have various inconsistently named shortcodes (e.g. `form`, `element_chart`). To avoid conflicts with other plugins as well as to make things easier for autocompletion and to keep things consistent it might be reasonable to switch to the following naming schema: e.g. `torro_form`, `torro_chart` and so on.

**Comment by felixarntz** [comment]
Prefixed shortcodes will be part of the refactored version (see #348). The existing shortcodes will still work for a bit, but be deprecated.
