### ISSUE TITLE
Change german translation of field name

### ISSUE THREAD

**Issue by zottto** [awsmug/torro-forms#275]
The field is named "Einfach-Antwort" (for the radio boxes), but the chechboxes are called "Mehrfach-Auswahl". The radio boxes should be named "Einfach-Auswahl".

Marc

**Comment by tyrann0us** [comment]
@zottto: see here: https://translate.wordpress.org/projects/wp-plugins/torro-forms/dev/de/default?filters[status]=either&filters[original_id]=2837443&filters[translation_id]=44582217
