### ISSUE TITLE
Keyboard shortcuts not possible while renaming a page

### ISSUE THREAD

**Issue by zottto** [awsmug/torro-forms#277]
If I try to rename a page (double-click on page name), it is not possibe to jump to the start of the input field with the keyboard shortcut "Shift"+"Pos1". Also "Shift"+"End" to jump to the end is not possible.
The field looses focus and is not editable anymore.

Edit: Also jumping to the front only with "Pos1" / jumping to the end with "End" is not possible.

Thanks,
Marc

**Comment by felixarntz** [comment]
This is no longer an issue in the refactored version.
