### ISSUE TITLE
Visible element name is not correctly shown on page 2

### ISSUE THREAD

**Issue by zottto** [awsmug/torro-forms#279]
On page one, if I enter a label name, the widget for the element is renamed accordingly (also if the element is closed).
If I add a second page, the elements are not renamed anymore, but still have their default names (like "Textfeld").

After saving the form (and reloading) the names are shown correctly.
But: after saving, the form builder is again on page one, although I was on page 2 when I clickes "Save"
Expected behaviour would be, to come back to page 2 after saving.

Thanks,
Marc

**Comment by felixarntz** [comment]
The problem with the element names is no longer an issue in the refactored version.

Saving the form's state (currently opened page) is an enhancement, separate from that. I opened #367 for further discussion/work on that.
