### ISSUE TITLE
Enhancement: Container element

### ISSUE THREAD

**Issue by zottto** [awsmug/torro-forms#280]
It would be nice to have a container element (fieldset), to organize fields. Pages are one way to organize elements and also separators, but sometimes it is useful to wrap some elements in one parent element (e.g. to expand/collapse it or to show/hide).

Thanks,
Marc

**Comment by mahype** [comment]
Hi Marc,

Pages are containers. We just named it pages at the moment for better understanding what you are doing and at the moment we are running one after another. There is no hierachy between containers at the moment. Maybe we need something like that. Another idea would be that you can handle a container like an element. Then you could nest a container. What do you think about that?

Greetings,

Sven

**Comment by zottto** [comment]
A container as an element was what I thought about when I wrote this issue. Because there is an HTML element for that (fieldset) I think it would be nice to have this feature in Torro Forms.

Marc
