### ISSUE TITLE
Three default placeholder strings inside settings aren't localized yet (beta 6)

### ISSUE THREAD

**Issue by rpkoller** [awsmug/torro-forms#282]
Inside the general settings three default placeholder strings aren't localized yet. Unsure haven't checked the develop branch yet.

![bildschirmfoto 2016-08-07 um 19 23 20](https://cloud.githubusercontent.com/assets/1665422/17464042/6e177a68-5cd5-11e6-9a85-7a018d2c15ae.png)

**Comment by mahype** [comment]
Hi Ralph,

thank you! :) Thats because its the develope version. I will translate the strings after I have deployed beta 7. I will release the beta today.

Greetings,

Sven

**Comment by rpkoller** [comment]
yep i know, no rush. it should have been just some sort of sticky note that that those fields don't slip through and get forgotten before the final. ;)

**Comment by mahype** [comment]
I will left this ticket open until I have translated it :)

**Comment by mahype** [comment]
I made the strings translatable. This just have to been updated in the next version on wordpress.org.
