### ISSUE TITLE
Redesign the create/edit form dialogue

### ISSUE THREAD

**Issue by rpkoller** [awsmug/torro-forms#284]
I try to write up a few thoughts I already talked about with @mahype regarding the redesign and possible improvement of the create and edit forms dialogue as a starting point for a further discussion. 

My hassle with the current implementation of form creation and editing is two fold. It adheres to the WordPress interface schema, that is well done, but there are still two flaws in my humble opinion. The first is a contextual one I already voiced in https://github.com/awsmug/torro-forms/issues/272 the other is mostly in regard of usability and accessibility. In the current state you have a spatial separation between the elements widget and the forms widget. 

![bildschirmfoto 2016-08-19 um 10 55 46](https://cloud.githubusercontent.com/assets/1665422/17804348/89a7303c-65fb-11e6-923f-7b8f09e6b972.png)

The user has to make the abstraction by first reading "drop your elements here" and the "elements" widget and then try the drag and drop. Technically very well done but i am uncertain and doubt all the users will figure things out immediately since the pattern isn't a common WordPress one. It is shiny but then has a far more troubling flaw. Performing the population of the pages with form elements within e.g. a screenreader might be a tough one. ;) 

There for I wanted suggest a solution similar to Advanced Custom Fields Pro. I visualize the suggested steps with screenshots and a video. 

At first I would suggest to remove the forms elements widget completely. You just go with a simple add element button at the bottom of the widget like here: 

![bildschirmfoto 2016-08-19 um 11 03 23](https://cloud.githubusercontent.com/assets/1665422/17804717/2a45b4a4-65fd-11e6-843c-06381ba20db6.png)

The basic workflow for adding removing and altering the position of a field looks something like that in ACF. 

https://dl.dropboxusercontent.com/u/8578/acf.mov

You add new fields with the button at the bottom. Afterwards you are able to alter the position by drag and drop. And for the field you mouse over you get options like edit, duplicate, move (to another field group) and delete. The only thing missing (I thought ACF initially also had that) was the ability to move a field one position up and down by a button as well; that was the main reason I suggested the solution to Sven in the first place. I would extend the shown approach by adding to the particular field you mouse over two vertically aligned buttons on the far right for moving the field one step up and down. Would make the whole elements setup manageable by keyboard as well as accessible. 

The last point I am not sure about is how to handle the visual display of pages. There are two approaches: 
## Torro Forms:

 You have one to x page buttons plus an add new page button. Spatially separated beneath the widget is the delete page button

![bildschirmfoto 2016-08-19 um 11 22 54](https://cloud.githubusercontent.com/assets/1665422/17805324/5369e268-65ff-11e6-8d6a-28e057327b1b.png)
## Advanced Custom Fields

Eliot solved the issue by introducing a "tab" field. 

![bildschirmfoto 2016-08-19 um 11 24 59](https://cloud.githubusercontent.com/assets/1665422/17805396/ab1936a8-65ff-11e6-998e-593817414fdc.png)

Basically all fields after a tab field are included within until the next tab field is placed. Tab1 contains field and flexi while Tab2 contains the repeater field. 

I am uncertain cuz each solution has its flaws. Basically I would go with some user tests here first. Or maybe you could go with a mix of both solutions. You might add a new tab element by the plus button at the bottom like in ACF and then a page button is created accordingly above like in Torro Forms at the moment alongside accordingly. You have a visual representation at the top of the elements list like in Torro Forms at the moment but also within the elements list itself like in ACF. And in that top pages list you might bring in the delete page button up form the bottom so everything is included in the same context (Maybe move it to the far right).  But in that regard i am totally uncertain and haven't come up with the right solution in my humble opinion. 

That's it for now. Thoughts?

**Comment by felixarntz** [comment]
The UI has been reworked as part of the refactoring, and the elements metabox has been removed. It's now replaced via an expandable area that is shown when "Add element" is clicked, so the main concern of this ticket should be resolved.

Further UI work should go into future efforts related to Gutenberg compatibility.
