### ISSUE TITLE
Unable to delete Page 1 (Beta 7)

### ISSUE THREAD

**Issue by rpkoller** [awsmug/torro-forms#285]
It feels a bit odd if you have created a few pages and try to delete the first page you are unable to cuz the delete button isn't shown 

![bildschirmfoto 2016-08-19 um 11 49 04](https://cloud.githubusercontent.com/assets/1665422/17806182/613b6cb4-6603-11e6-814b-87edf2ebeb6d.png)

While for all other pages it is possible. 

![bildschirmfoto 2016-08-19 um 11 49 24](https://cloud.githubusercontent.com/assets/1665422/17806187/6adfeccc-6603-11e6-9b00-14de0b4271ed.png)

Is there a technical reason that that option isn't offered?

**Comment by mahype** [comment]
I have fixed that issue
