### ISSUE TITLE
Possibility to define one checkbox / radio button as pre-selected

### ISSUE THREAD

**Issue by zottto** [awsmug/torro-forms#288]
In a list of checkboxes or radio buttons it would be nice to have the possibility to select one of the elements (radio buttons) or even multiple elements (checkboxes) as pre-selected.

**Comment by mahype** [comment]
This is already possible. Here is the list of all elements:

Textfield, Textarea, Onechoice, Dropdown
?torro_input_value_ELEMENTID=VALUE

Multiple Choice for one value
?torro_input_value_ELEMENTID[]=VALUE1

Multiple Choice for multiple values
?torro_input_value_ELEMENTID[]=VALUE1&torro_input_value_ELEMENTID[]=VALUE2

Thats it! :)

**Comment by mahype** [comment]
Or take a look here: Ticket #70
