### ISSUE TITLE
E-Mail-Benachrichtigung Platzhalter lassen sich nicht auswählen

### ISSUE THREAD

**Issue by 00Sleepy** [awsmug/torro-forms#291]
Wenn ich in der E-Mail-Benachrichtigung über das + Symbol einen Platzhalter auswähle wird dieser nicht in das Feld eingefügt. Problem mit WP 4.6 und TF 1.0.0beta7

**Comment by 00Sleepy** [comment]
In einer anderen Installation mit WordPress 4.6.1-alpha-38339 ist dieser Fehler nicht vorhanden.

**Comment by mahype** [comment]
Danke Dir!

**Comment by mahype** [comment]
Also ich kann das jetzt auch nicht mehr reproduzieren. Ich schließe das Ticket und mache es ggf. wieder auf, sollte es wieder Probleme an der Stelle geben.
