### ISSUE TITLE
Formular Shortcode Copy to Clipboard Button doesn't work

### ISSUE THREAD

**Issue by 00Sleepy** [awsmug/torro-forms#292]
Der "Copy to Clipboard" Button für den Formular Shortcode funktioniert nicht.

WP 4.6 und TF 1.0.0beta7

**Comment by 00Sleepy** [comment]
In einer anderen Installation mit WordPress 4.6.1-alpha-38339 ist dieser Fehler nicht vorhanden.

**Comment by mahype** [comment]
Daaaanke! Ich schaus mir mal an.

**Comment by mahype** [comment]
Sag mal kannst Du mir sagen wie Deine Systemkonfiguration ist? OS, Browser, Versionen usw.?

**Comment by mahype** [comment]
Ich habe das jetzt auf dem Mac mit Chrome, Firefox und Safari auf WordPress 4.6.1 getestet. Ich kann das leider nicht reproduzieren.
