### ISSUE TITLE
Add possibility to change error text per field

### ISSUE THREAD

**Issue by zottto** [awsmug/torro-forms#294]
The error message shown on form submit is based on the user language. There is no possibility to adjust the message and make it more detailed (e.g. not only "You must enter something." but "Please enter the correct IBAN".). This is not possible at the moment.

It would be nice to have a field in the field settings for an individual error message that overwrites the default message.

Thanks,
Marc ;-)

**Comment by mahype** [comment]
Hi Marc,

just download the latest develope version of Torro Forms and take a look here:
https://torro-forms.com/adding-extra-validations-elements/

I have added an filter hook that you can add your own validations now.

Greetings,

Sven
