### ISSUE TITLE
Add possibility for password fields

### ISSUE THREAD

**Issue by zottto** [awsmug/torro-forms#295]
Add possibility to add fields of type password that do not show the keyboard input on the screen.

Thanks,
Marc

**Comment by mahype** [comment]
Added.

![edit_form_ _plugin_tests_ _wordpress_-_2016-10-09_13 19 01](https://cloud.githubusercontent.com/assets/663697/19219986/fe298b68-8e22-11e6-8ea5-14c75c4a415e.png)
