### ISSUE TITLE
Change multiple choice results in excel.

### ISSUE THREAD

**Issue by hutsori** [awsmug/torro-forms#296]
Hi Sven, 

I know we have discussed about this while go. 

Currently multiple choice questions show like this:

> Your favorite fruit?
> 1. apple   (select)
> 2. orange
> 3. watermelon
> 4. grape  (select)

In Excel export, 

> Your favorite fruit?   Your favorite fruit?  Your favorite fruit?  Your favorite fruit?
>            yes                            no                       no                             yes
> 

Can we change this to:

> Your favorite fruit?
> apple, grape

After working with the excel file for a while, I figured this would be so much easier to see the results. (And google forms does this way too)

**Comment by mahype** [comment]
What you describe is exactly what should happen. I will check and change it.

**Comment by mahype** [comment]
I checked out and cannot reproduce your Excel export. In the moment it's like this:

![bildschirmfoto-2016-10-09-um-13 26 58- 2](https://cloud.githubusercontent.com/assets/663697/19220045/9262369e-8e24-11e6-9c46-01860dec4cbc.png)

**Comment by hutsori** [comment]
Yes torro-form currently outputs like that, but I am saying it'd be so much easier to see if it outputs this way:
<img src="http://i.imgur.com/8D0wNLq.png">
