### ISSUE TITLE
PHP Notices

### ISSUE THREAD

**Issue by Horttcore** [awsmug/torro-forms#297]
Ich bekomme in der Ausgabe ein paar `Notices`, nicht weiter tragisch aber ich dachte ich meld es mal.

`Notice: Undefined variable: element_id in …/core/element-types/base-element-types/textfield.php on line 65`
`Notice: Undefined variable: element_id in …/core/element-types/base-element-types/textarea.php on line 58`

**Comment by tyrann0us** [comment]
Duplicate of #290.

**Comment by mahype** [comment]
I have closed the ticket. Please check ticket #290 for this. But thank you for submitting! :)
