### ISSUE TITLE
Forms Manager - Arguments swapped from parent to child class

### ISSUE THREAD

**Issue by schlessera** [awsmug/torro-forms#305]
The class `Torro_Forms_Manager` seems to swap the arguments for the `create` method call around. This is either a bug or at least breaking OOP principles.

Signature in parent class:
`public function create( $superior_id, $args = array() );`

Signature in child class:
`public function create( $args = array(), $invalid = false );`

**Comment by felixarntz** [comment]
This is invalid as of the refactored version (see #348).
