### ISSUE TITLE
Magic methods override encapsulation

### ISSUE THREAD

**Issue by schlessera** [awsmug/torro-forms#317]
Although the plugin uses lots of classes with private and protected properties, most of these inherit magic `__get()` and `__set()` methods that completely eliminate any access control.

So, as an example, if I have an instance `$foo` of a class that has a private property `$bar`, this property can be set by any outside code by simply calling `$foo->bar = $new_value;`.

The end result is that the entire encapsulation system is rendered ineffective.

**Comment by felixarntz** [comment]
This is no longer an issue as of #348.
