### ISSUE TITLE
Avoid `method_exists` through inheritance

### ISSUE THREAD

**Issue by schlessera** [awsmug/torro-forms#318]
When using classes, you should make real use of inheritance.

Code like this:

```PHP
private function base_init() {
	if ( method_exists( $this, 'includes' ) ) {
		$this->includes();
	}
}
```

should be replaced by something like this:

```PHP
private function base_init() {
	$this->includes();
}

private function includes() {
	// Override in child class to add includes.
}
```

**Comment by mahype** [comment]
Merged!

**Comment by felixarntz** [comment]
This is no longer an issue as of #348. There are still some `method_exists()` checks in the plugin, however these have a different background and have to do with "kind of unusual" usage of traits.
