### ISSUE TITLE
Self-instantiating classes

### ISSUE THREAD

**Issue by schlessera** [awsmug/torro-forms#320]
Classes should not instantiate themselves in the file they are being declared in (by having a `new MyClass();` or a `MyClass::instance();` at the bottom of the file).

- This makes unit testing hard or impossible. You cannot load the class without it immediately becoming active. Just having the class being declared and calling one single method is not feasible.

- You can't use an autoloader, as the point of instantiation is not controllable anymore.

Some different entity (like a Controller, a Container, ...) should be responsible for doing the instantiations, so that loading and instantiation can be decoupled.

**Comment by felixarntz** [comment]
Autoloading and getting rid of singletons (a.k.a. classes instantiating themselves in this case) is part of the refactoring and was done via #348.
