### ISSUE TITLE
PHP 5.2 makes code unnecessarily bloated

### ISSUE THREAD

**Issue by schlessera** [awsmug/torro-forms#321]
I saw in the contribution guidelines that the code must be compatible with PHP 5.2.

Disregarding the fact that I would recommend against using Singletons (for several reasons), I would suggest thinking about bumping at least to PHP 5.3 to be able to use late static binding.

This would remove all of the `$instance` properties and the `instance()` methods from the subclasses, as you can add them once into the base class and be done with it, using:

```PHP
public static function instance() {
	if ( null === static::$_instance ) {
		static::$_instance = new static();
	}
	return static::$_instance;
}
```

Note the `static` instead of the `self`.

**Comment by mahype** [comment]
As I decided with @felixarntz, I have bumped the version of compatibility to PHP 5.4.

**Comment by schlessera** [comment]
Great! You would really recommend cleaning up the subclasses then and having this instancing code in one place.

Better yet, get rid of it entirely through something like described in #322 . You can still add static Facades to have easy access to everything, but it will be much cleaner/more flexible behind the scenes.

**Comment by felixarntz** [comment]
This will no longer be an issue as of #348, Torro Forms will require PHP >= 5.6.
