### ISSUE TITLE
Central Container to manage instances

### ISSUE THREAD

**Issue by schlessera** [awsmug/torro-forms#322]
Almost every class is a Singleton and has a method for fetching its instance.

I would recommend building a central container (like a Registry or a Service Locator) that can be used to get the instances. `torro()` could be the entry point to get access to the container, so this would probably be easily adapted.

Having the instances be managed through such a central container allows you to let the container decide on a class-by-class basis what classes to share (always passing the same instance) or not (always creating a new instance to hand out). This gets rid of the Singletons and let's you fake/mock individual classes easily for proper unit tests.

**Comment by felixarntz** [comment]
Singletons are no longer used in the refactored version (see #348). All services are available through `torro()->name_of_service()` and commonly passed where needed via dependency injection.
