### ISSUE TITLE
Misleading signatures for `copy()`

### ISSUE THREAD

**Issue by schlessera** [awsmug/torro-forms#324]
The `copy()` operation that is declared in `Torro_Instance` has a different signature than the overrides that were done in the subclasses.

Signature in `Torro_Instance_Manager`:
```PHP
public function copy( $id, $superior_id );
```

Signature in `Torro_Forms_Manager extends Torro_Instance_Manager`:
```PHP
public function copy( $id, $args = array() );
```

This is not only misleading and should be considered a bug. PHP does not allow method overloading. Instead, the method is replaced, making the calls between different instances break.

**Comment by felixarntz** [comment]
This will be fixed via the refactoring (see #348).
