### ISSUE TITLE
New form: Duplicate id of form type input

### ISSUE THREAD

**Issue by tyrann0us** [awsmug/torro-forms#325]
I created a new form and noticed that the `id` of the form type input gets repeated multiple times.

![image](https://cloud.githubusercontent.com/assets/8144115/19923002/866bf590-a0e5-11e6-8d85-2d617c826327.png)

Basically if you add multiple text fields the "type input" will look like this for all fields:
`<input type="radio" id="settings_temp_id_314534_2" name="containers[temp_id_219716][elements][temp_id_116457][settings][temp_id_314534][value]" value="email_address">`

This causes the page to jump to the first input and checking it if you click on a label of one of the other inputs.

After I saved the form the `id`s became unique.

**Comment by mahype** [comment]
Thank you for reporting! I will have a look on that!

**Comment by mahype** [comment]
This should be fixed now in the actual develop version and will come with 1.0.0 beta 8.
