### ISSUE TITLE
One Element with multiple inputs

### ISSUE THREAD

**Issue by websupporter** [awsmug/torro-forms#329]
If you create your own element, you might want to have a lot of input fields. You can do so and save them all serialized or as JSON (I guess another way would be quite difficult from the architectural point of view) Using the methods `render_value()` and `render_value_for_export()` you are able to deserialize them and display them as you wish.

However, you can't display them as seperate entities. This would be very useful for the CSV Export for example.

Lets say you work on an address element with several input fields. Right now the whole address - street, zip, city, state, country can be only one column in the CSV. I would love to be able to split them (at least here) in several columns.

Another idea, which came to my mind was to have something like "Element Groups", you could develop. So you would drag the element group "Address block" into form and such a group would internally consist out of several Elements.

This where just my thoughts on working with multiple data in one element.

Possible use cases:
* Address blocks
* Store Lat and Lon in different fields
* Predefined fieldsets needed by third parties to analyze data

Thanks for this awesome plugin. Olá

**Comment by mahype** [comment]
Oh thats a good point! We definetly will work on that. I will talk with @felixarntz how to implement it. But this is so basic, that it will come before we launch the first stable version.

**Comment by websupporter** [comment]
Well, I am not quite sure. It would be certainly nice to have also in the database multiple rows to use, but I was playing around a bit. For me the export is important. Even the HTML table for the entry does not matter to much. But I was playing there a bit too.

I have created a branch here: https://github.com/websupporter/torro-forms/commits/filter-all-results-via-element

If you add it like this, you could extend the `Torro_Element_Type` with the methods `export_results()` and `render_value_column_html()`. I think right now, the `export_results()` ist quite hacky. First I was thinking about a filter, but I think it fits the architecture better to return it to the element, but I am not sure.

So anyway, those methods would allow you to split a single row (lets say you have JSON data here) into multiple rows on output if you wish. For example:

```


	/**
	 * Filter the results for export
	 *
	 * @param array         $results The current results.
	 * @param Torro_Element $element The current element.
	 *
	 * @return array
	 */
	public function export_results( $results, $element ) {

		$label = $element->label;
		foreach ( $results as $key => $result ) {
			$data = (array) json_decode( $result[ $label ] );
			unset( $result[ $label ] );
			$result = array_merge( $result, $data );
			$results[ $key ] = $result;
		}

		return $results;
	}

	/**
	 * Render the result column HTML.
	 *
	 * @param string $html
	 * @param string $value
	 *
	 * @return string
	 */
	public function render_value_column_html( $html, $value ) {

		$values = (array) json_decode( $value );
		$html = '';
		foreach ( $values as $key => $val ) {
			$html .= '<tr><td>' . $key . '</td><td>' . $val . '</td></tr>';
		}
		
		return $html;
	}
```

**Comment by felixarntz** [comment]
Multi-field support for elements will be available in the refactored version. API details coming soon. :)

Done via #348.
