### ISSUE TITLE
Undefined property on page overview in backend

### ISSUE THREAD

**Issue by mheiduk** [awsmug/torro-forms#336]
Hi,

on a fresh Wordpress install without any other plugins activated I get the following info notices on the page overview site in the backend:

`Notice: Undefined property: stdClass::$post_type in /wp-content/plugins/torro-forms/core/form-controller.php on line 256`

`Notice: Undefined property: stdClass::$post_content in /wp-content/plugins/torro-forms/core/form-controller.php on line 261`

`Notice: Undefined property: stdClass::$post_content in /wp-content/plugins/torro-forms/components/results/shortcodes.php on line 56`

With every new page the last info with shortcodes.php gets duplicated.

Thanks for your help!

Best,
Marc

**Comment by sknopp** [comment]
As a workaround (don't know if it's a solution) i added the following just before the critical lines:
`
if(empty($post->post_type)){
return;
}
`

**Comment by felixarntz** [comment]
This will be invalid/fixed via #348.
