### ISSUE TITLE
Set User Role based permissions in Torro Forms Settings

### ISSUE THREAD

**Issue by ginocremer** [awsmug/torro-forms#337]
For the moment it seems not possible to define which user role can access Torro Forms. For the moment even contributors can create forms and access forms created by admins. For a customer project we have to limit access to Torro Forms just to editors (or editors and admins then).

Or is there another way by using a hook to set a capability limit?

**Comment by tyrann0us** [comment]
See this page for a tutorial on how to write your own `Form Access Control` class: https://torro-forms.com/api/extending/form-access-control/.

**Comment by felixarntz** [comment]
@ginocremer If I understand you correctly, you're referring to the capabilities for logged-in users to manage forms. There is no filter in the plugin to adjust this, however Core itself has one: With [`register_post_type_args`](https://developer.wordpress.org/reference/hooks/register_post_type_args/) you can adjust the arguments used to register a post type, all you need to do is check whether the `$post_type` parameter of the filter is `torro_form`.

**Comment by ginocremer** [comment]
Hi Felix, thank you. Worked like a charm. Now simple Subscribers can't add forms. But: They can still reach the settings page. Is there a way to extend my filter-function to disallow this too? 

Here is my new filter-function (feel free to extend or rewrite) :-) : 

add_filter( 'register_post_type_args', 'change_capabilities_torro_forms' , 10, 2 );
function change_capabilities_torro_forms( $args, $post_type ){
 if ( 'torro_form' !== $post_type ) {
     return $args;
 }
 $args['capability_type'] = 'delete_others_pages'; // Editors and Admins only
  return $args;
}

Thank you very much :-)

**Comment by felixarntz** [comment]
Adding a note, that we should possibly make this more flexible soon.

**Comment by felixarntz** [comment]
The refactored version comes with custom capabilities for everything, allowing to easily adjust things like who can manage forms, who can manage form submissions, who can manage form settings etc. More details later. Done via #348.
