### ISSUE TITLE
limit of PHP max_num_fields! (1413 of 1000)

### ISSUE THREAD

**Issue by samclough** [awsmug/torro-forms#340]
Hi guys,

Firstly thanks for this great plugin:)

I've just got the message: 'You are over the limit of PHP max_num_fields! (1413 of 1000)
Please increase the value by adding php_value max_input_vars [NUMBER OF INPUT VARS] in your htaccess or contact your hoster. Otherwise your form can not be saved correct.'

Which php file exactly do I need to add this code?
Secondly, can it be done by changing the file itself in the zip-folder I downloaded for this plugin and then reinstalling the plugin? Am having trouble getting access within our organisation :) SAm

**Comment by zu** [comment]
If you don't have access to the php.ini (which many hosting panels offers via GUI) you might try to add 

`php_value max_input_vars 2000` to the .htaccess file directly in the root of your wordpress installation.

It is not always working. It depends on the configuration of the server.

Maybe just use more than one form to get that many information.

If you only have one form and the user makes a mistake or the browser is crashing he might loose all entered data at once which is a very bad experience ;-)

**Comment by samclough** [comment]
Holy shit
Thank you it worked very well ☺ Sam

**Comment by felixarntz** [comment]
This doesn't need to be changed on the plugin side.
