### ISSUE TITLE
reCAPTCHA not checking I am not robot

### ISSUE THREAD

**Issue by eic** [awsmug/torro-forms#342]
Hi,

I am having a strage behavior using/testing a form with reCAPTCHA.
My form has some fields, all of them mandatory and enabled reCAPTCHA v2.

As first test I try to submit the empty form. I get errors telling my I have to input something and I get a error "Missing reCAPTCHA response".
Fine.

Next I type some values in the form filds but I am NOT checking the "I am not robot" checkbox of reCAPTCHA.
After hitting submit my form gets submitted.
WTF!?!

I am not an expert with reCAPTCHA but in my understanding I have to check the "I am not robot" checkbox in either case to pass.
Or is there some magic working in the background that proofs im an not a spam bot?

**Comment by eic** [comment]
OK, something I have found:
In torro-forms/components/form-settings/base-form-settings/spam-protection.php some filters are defined.
```
add_filter( 'torro_response_status', array( $this, 'check_recaptcha_submission' ), 10, 4 );
add_filter( 'torro_response_status', array( $this, 'check_honeypot_submission' ), 10, 4 );
add_filter( 'torro_response_status', array( $this, 'check_timetrap_submission' ), 10, 4 );
```
All of them running on same priority.

But what if check_recaptcha_submission runs first and returns false and check_honeypot_submission and check_timetrap_submission later and return true?
The result of spam protection is the result of the last filter function executed?

After deactivation of check_honeypot_submission and check_timetrap_submission the reCAPTCHA behavior works like I expect it.
For me this is a temporary fix.

Maybe it is an good idea to check the $status input if some prev filter set it to false.
So if one spam dedection mechanism recognize spam it should not overruled by a filter running later.

**Comment by sknopp** [comment]
i had the same problem and also found the solution:

the error is in the `check_timetrap_submission()` function which currently returns `true` or `false` instead of setting the $status variable.

function needs to look as follows:
```php
public function check_timetrap_submission( $status, $form_id, $container_id, $is_submit = false ) {
	if ( $this->is_timetrap_enabled( $form_id )  ) {
		if( array_key_exists( 'timestamp', $_REQUEST ) && ! empty( $_REQUEST[ 'timestamp' ] ) && ( time() - (int) $_REQUEST[ 'timestamp' ] <= (int) $this->timetrap_time ) ) {
			$this->errors[ $form_id ] = __( 'Go away!', 'torro-forms' );
			$status = false;
		}
	}
	return $status;
}
```

**Comment by felixarntz** [comment]
Fixed as part of the refactoring
