### ISSUE TITLE
how to read setting 

### ISSUE THREAD

**Issue by raaaas** [awsmug/torro-forms#350]
ok i made this change 

			'left'	=> array(
				'title'			=> __( 'left box', 'torro-forms' ),
				'type'			=> 'textarea',
				'description'	=> __( 'The description will be shown after the input.', 'torro-forms' ),
				'default'		=> ''
			),
			'right'	=> array(
				'title'			=> __( 'right box', 'torro-forms' ),
				'type'			=> 'textarea',
				'description'	=> __( 'The description will be shown after the input.', 'torro-forms' ),
				'default'		=> ''
			),

to Setting_Fields , now i want to load them to elements but there is no manual for it

can you just give me a hint ?

**Comment by felixarntz** [comment]
This is a support question, not a plugin issue. We will soon rework the full documentation to account for the refactored version.
