### ISSUE TITLE
"tinymce is not defined" Error on adding form fields to notification

### ISSUE THREAD

**Issue by sknopp** [awsmug/torro-forms#351]
![button](https://user-images.githubusercontent.com/10382820/29742404-008148a2-8a7f-11e7-847a-7c8c31a09e5e.PNG)

When i try to add form fields to a notification, i get the following error:

![error1](https://user-images.githubusercontent.com/10382820/29742403-f603befa-8a7e-11e7-92e3-8c44e7902e3f.PNG)

typing ```tinymce = false``` to console helps for the upper fields but not for the message textarea.

I would try to tell you more details but i don't want to debug minified js-code. But it seems like it's easy to fix.

**Comment by mahype** [comment]
Hi!

Thanks for reporting! We are refactoring the plugin at the moment and this will be one of the parts which will be totally rewritten, because WordPress has renewed  the editor in one of the last versions.

Greetings,

Sven

**Comment by felixarntz** [comment]
Fixed as part of the refactoring.
