### ISSUE TITLE
Adding custom element-type in multipage form leads to loosing previous pages values

### ISSUE THREAD

**Issue by sknopp** [awsmug/torro-forms#352]
I've added a custom element-type as described here: https://torro-forms.com/api/extending/elements/
The element is shown on the second last page of my multipage form. But when i look into the result entries, only the inputs of the elements from this page and later are saved. Earlier pages inputs are getting lost.

I already checked the POST values with Chrome Dev Tools, they are submitted the same way as without my element. I commented out the custom contents of my element-type validate() function, but still missing the first pages values.

Where do the values get cached between pages?

If this matters: In my element-type i'm opening an inner query for looping through a custom post-type for my checkbox-options. May i have to consider something here?

**Comment by felixarntz** [comment]
The refactored version will completely change how element types need to be handled. Please refer to upcoming documentation for this.
