### ISSUE TITLE
Slow loading of backend form with many results

### ISSUE THREAD

**Issue by mheiduk** [awsmug/torro-forms#354]
Hi,
we're using torro forms for a while now, especially for competitions. Some competitions are getting more than 1000 participants, therefore many entries have to be loaded when we are viewing the form in the backend or export the participants via csv/xls. The loading gets slower for each new participant and I am scared that the script will exit when the runtime is reached.

Do you already know of this problem respectively are you working on a solution? Apart from that, really great plugin, saved me a lot of work! Thanks!

Best regards,
Marc

**Comment by mahype** [comment]
Hi Marc,

we are working on Torro Forms and we have totally reworked the plugin right now and are near to finish. We have splitted the pariticipants to a new section named "Submission" that the performance in the backend should be a lot better. I think we will release the new version at the beginning of the new year. But until we release we have to test, test and test...

Greetings,

Sven

**Comment by felixarntz** [comment]
As part of the refactoring, the plugin is now much more scalable, specifically in that regard.
