### ISSUE TITLE
Enabled checkbox should disappear

### ISSUE THREAD

**Issue by mahype** [awsmug/torro-forms#364]
Like the motto "Decisions not options", the checkboxes for "Enable in every tab should disappear if possible. The values in the following form fields should be neutral if not set.

**Comment by felixarntz** [comment]
4e94b9b removes the checkbox where it is not needed. In some cases however it is still necessary, when there is no other way to determine whether a module is active or not.

The default for new modules is still to display such a checkbox to make it easier for developers, but it can be easily overridden, similar as seen in this commit.
