### ISSUE TITLE
Select Field is not fitting

### ISSUE THREAD

**Issue by mahype** [awsmug/torro-forms#370]
![bildschirmfoto 2017-12-10 um 12 02 57](https://user-images.githubusercontent.com/663697/33804291-2c4de2bc-dda2-11e7-8fb9-5a8f713ee39e.png)

Iike in the above screenshot, the select field is not fitting. It should have a minimum horizontal size and should be also fitting the length of the content.

**Comment by felixarntz** [comment]
This has been fixed upstream in the plugin-lib, see https://github.com/felixarntz/plugin-lib/commit/ace6777e9c293137730dabccf6a80260306ffffb
