### ISSUE TITLE
Descriptions light

### ISSUE THREAD

**Issue by mahype** [awsmug/torro-forms#372]
![bildschirmfoto-2017-12-10-um-12 11 48- 2](https://user-images.githubusercontent.com/663697/33804389-e11b807c-dda3-11e7-862d-dfcab52645db.jpg)

We should make the formbuilder more light. To many text is not helpful and occurs disorientation. I have an example in the screenshot how WooCommerce made it. They have a Questionmark before the form fields with a mouseover and the explaining text. But we should get sure that we keep the frontend accessible.

**Comment by felixarntz** [comment]
Fixed in dd5c60eab272950bd5b7c2745bfc7607b381f0d6
