### ISSUE TITLE
Fatal error: Class 'Leaves_And_Love_Plugin' not found

### ISSUE THREAD

**Issue by eic** [awsmug/torro-forms#391]
Im trying the new version taged 1.0.0-beta.8 and getting this:

`Fatal error: Class 'Leaves_And_Love_Plugin' not found`

Something I miss?

**Comment by mahype** [comment]
Hi,

this is not the new version. This is the old version. If you want to download the actual develope version you can do it here at the moment: 

https://github.com/awsmug/torro-forms/tree/download

The version beta 9 will be the totally renewed version, which will come an march 5th.

Sven
