### ISSUE TITLE
 fatal error-- torro-forms.php on line 44

### ISSUE THREAD

**Issue by alexlii1971** [awsmug/torro-forms#392]
Plugin could not be activated because it triggered a fatal error.
Fatal error: Class 'Leaves_And_Love_Plugin' not found in /var/www/mysite.com/htdocs/wp-content/plugins/torro-forms-master/src/torro-forms.php on line 44

Please check the screenshot：http://prntscr.com/j56o3w

our environment：

Server info: |   | nginx/1.10.0
-- | -- | --
PHP version: |   | 5.6.33-0+deb8u1
WP version: |   | 4.9.4
-- | -- | --
WP multisite: |   |  
WP memory limit: |   | 256 MB
WP debug mode: |   |  

and I activated it in a sub site.

Alex

**Comment by tyrann0us** [comment]
Run `composer update` in plugin root.
Note: Maybe wait until [`v1.0.0-beta-9`](https://github.com/awsmug/torro-forms/milestone/12) is officially released. The download will contain the "full" plugin.

**Comment by mahype** [comment]
Hi Alex,

the update to Torro Forms 1.0.0 beta 9 schould come out tomorrow.

Kind regards,

Sven

**Comment by alexlii1971** [comment]
Sounds great, and I will test it.
 Alexlee

      发件人： Sven Wagener <notifications@github.com>
 收件人： awsmug/torro-forms <torro-forms@noreply.github.com> 
抄送： alexlii <alexlii@yahoo.com>; Author <author@noreply.github.com>
 发送日期： 2018年4月16日, 星期一, 上午 4:12
 主题: Re: [awsmug/torro-forms] fatal error-- torro-forms.php on line 44 (#392)
   
Hi Alex,the update to Torro Forms 1.0.0 beta 9 schould come out tomorrow.Kind regards,Sven—

**Comment by alexlii1971** [comment]
Hello,

I just tested 1.0.0-beta.9 , and still I can not activated:

 http://prntscr.com/j699pe

Thanks.

**Comment by felixarntz** [comment]
@alexlii1971 Where and how did you download it?

**Comment by mahype** [comment]
It was from the repositoriy i think. @alexlii1971 Please update from the WordPress directory https://wordpress.org/plugins/torro-forms/.

**Comment by alexlii1971** [comment]
@felixarntz @mahype  Thanks, 

I download it from https://github.com/awsmug/torro-forms

and I tried the version from https://wordpress.org/plugins/torro-forms/.
and there is a issue report at: 
https://github.com/awsmug/torro-forms/issues/396

Alex

**Comment by felixarntz** [comment]
This happened because composer dependencies were not installed, so it’s not a bug.
