### ISSUE TITLE
Success message after submit

### ISSUE THREAD

**Issue by Soean** [awsmug/torro-forms#394]
## Issue Overview
When a user submits a form, he sees the message:
`You do not have access to this form submission.`
I want to show the user a success message, how could I do this?

**Comment by mahype** [comment]
Ok. We have to reproduce that and to fix this. Thank you for reporting! :)

**Comment by felixarntz** [comment]
@Soean Are you logged-in when seeing this or not? Which methods of user identification are activated for the form? I can’t currently replicate this issue.

**Comment by Soean** [comment]
Sorry, reseting the caching plugin solves the problem 🙈
