### ISSUE TITLE
Torro Forms capabilities are shown but not really minded inside the role editor of the Members plugin

### ISSUE THREAD

**Issue by rpkoller** [awsmug/torro-forms#399]
## Issue Overview

The available capabilities by Torro-Forms are shown in the Members Plugin role editor but neither as granted nor denied, but with an adminstrator account i am still able to do everything even no checkbox is checked. On a side note the capability name is shown with underscore and not in a prettified format. 

## Steps to Reproduce (for bugs)

1. Install & activate Torro Forms Beta 9 
2. Install & activate Members Plugin (https://github.com/justintadlock/members)
3. Go to users -> roles -> administrator -> forms or taxonomies with an administrator account

I am using Local by Flywheel with nginx, php 7.1.4, mysql 5.6.34, WordPress 4.9.5, Torro-Forms Beta 9 and Member 2.0.2 with Safari 11.1

## Expected Behavior

It would be nice if the capability names would be shown in a regular prettified way not with underscores and if inside the role editor certain capabilities would get default values. Like for the administrator role all capabilities granted for example. 

## Current Behavior

Currently it looks like that: 

![bildschirmfoto 2018-04-17 um 11 44 21](https://user-images.githubusercontent.com/1665422/38863283-6a11f012-4237-11e8-8031-f4339d8b7dfa.png)
![bildschirmfoto 2018-04-17 um 11 46 16](https://user-images.githubusercontent.com/1665422/38863289-7101b4ca-4237-11e8-883f-308203ab099c.png)

**Comment by felixarntz** [comment]
@rpkoller Torro Forms capabilities are not added to the database, instead they are mapped to others or granted dynamically via the `user_has_cap` or `map_meta_cap` filters. This is the recommended way for custom capabilities in plugins unless these plugins also introduce their own roles (which Torro Forms does not). Maybe the Members plugin doesn’t look at these filters correctly (tbh it may be relatively hard to accomplish that).

If you need to freely grant/deny Torro Forms capabilities, you can deactivate the entire mapping by calling `map_capabilities( false )` on all capability manager objects. See the `Torro_Forms::setup_capabilities()` method for the original setup. Deactivating mapping will essentially disable access to any of the plugin functionality until you grant those capabilities to a role.
