### ISSUE TITLE
Date, Time& Week different style in safari and chrome

### ISSUE THREAD

**Issue by alexlii1971** [awsmug/torro-forms#401]
Hello,

Date, Time& Week fields will automatically show up formatted form in Safari, but these does not show up in Mac safari, I am not sure whether it is a issue, please check:

http://prntscr.com/j6dbkb

Alex

**Comment by tyrann0us** [comment]
https://caniuse.com/#feat=input-datetime

**Comment by mahype** [comment]
Yes! Thats the problem. We are supporting the HTML5 input types, but not all browsers doing that correct. Maybe we have to think about that.
