### ISSUE TITLE
Adding method set_props()

### ISSUE THREAD

**Issue by mahype** [awsmug/torro-forms#403]
At the moment we can create an element in this way: 

`
$element = torro()->elements()->create();
$element->container_id = $container_id;
$element->label       = ‘Our Element’;
$element->type       = ‘textfield’;
$element_setting->sync_upstream();`

That is a lot of effort to  create an element. We should shorten it to:

`torro()->element()->create()->set_properties( array( 'container_id' => 123, 'label' => 'Our Element', 'type' => 'textfield' ) )->sync_upstream();`

**Comment by felixarntz** [comment]
Fixed via https://github.com/felixarntz/plugin-lib/commit/19dccf5eea312183480d15d0922502aa1ef0b8bd
