### ISSUE TITLE
Email notifications > Missing form element placeholders

### ISSUE THREAD

**Issue by mahype** [awsmug/torro-forms#405]
The element placeholders in the email notifications are not present. I have a created a contact form and saved it several times, but there none of the fields were shown in the placeholder list.

<img width="1166" alt="bildschirmfoto 2018-04-20 um 08 32 28" src="https://user-images.githubusercontent.com/663697/39034235-f8c4c8f8-4475-11e8-99ef-6aacb4036ea3.png">

**Comment by mahype** [comment]
As I could see now, the placeholders is not missing in every field. In the subject I can find all I need. But not in the fields before.

<img width="838" alt="bildschirmfoto 2018-04-20 um 08 41 19" src="https://user-images.githubusercontent.com/663697/39034462-c1e4b5c2-4476-11e8-8082-46ec7e2a62de.png">

**Comment by mahype** [comment]
If I click on the button for placeholders next to "Add Media", nothing happens.

**Comment by felixarntz** [comment]
Email address fields only show values which make sense to use as an email address. For example, you have to set the `input_type` of a field to `email` for that element to show up there.

One thing you mentioned is indeed a bug though: When adding a new email to the list, placeholders for the existing elements are not added to the lists. They are only added after saving and reloading the page. This needs to be fixed.

> If I click on the button for placeholders next to "Add Media", nothing happens.

I couldn't replicate this, and it is another issue than this one. If that bug persists for you, please create a separate issue.

**Comment by felixarntz** [comment]
I had the issue now too, opened #409 for it.
