### ISSUE TITLE
Email notifications > Fatal error after inserting {adminemail}

### ISSUE THREAD

**Issue by mahype** [awsmug/torro-forms#406]
After inserting the {adminemail} placeholder in the FROM field of an email notification, I get this Fatal Error after sending the form:

> Fatal error: Uncaught Error: Call to a member function manager() on null in /wp-content/plugins/torro-forms/src/modules/actions/module.php:73 Stack trace: #0 [internal function]: awsmug\Torro_Forms\Modules\Actions\Module->handle(Object(awsmug\Torro_Forms\DB_Objects\Submissions\Submission), Object(awsmug\Torro_Forms\DB_Objects\Forms\Form)) #1 /wp-content/plugins/torro-forms/vendor/felixarntz/plugin-lib/src/traits/hooks-trait.php(195): call_user_func_array(Array, Array) #2 /wp-includes/class-wp-hook.php(286): awsmug\Torro_Forms\Modules\Module->Leaves_And_Love\Plugin_Lib\Traits\{closure}(Object(awsmug\Torro_Forms\DB_Objects\Submissions\Submission), Object(awsmug\Torro_Forms\DB_Objects\Forms\Form)) #3 /wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array) #4 /wp-in in /wp-content/plugins/torro-forms/src/modules/actions/module.php on line 73

**Comment by Horttcore** [comment]
Happens for me too I've I add any email action to a form
