### ISSUE TITLE
Not saving after 23 questions

### ISSUE THREAD

**Issue by SudburyAC** [awsmug/torro-forms#420]
Is there a limit on the number of questions in one form?

I'm on page 5 question 30 and I can questions and answer fields, however when selecting update it does not retain the information.  I've tried entering one at a time, but still no luck.

**Comment by mahype** [comment]
No there is no limit. This should be a bug. We will take care about that!

Thank you for reporting!

**Comment by felixarntz** [comment]
Duplicate of #416 which is going to be fixed in the next release.

**Comment by SudburyAC** [comment]
I see two updates went through, however I still can't add more
questions/pages as they are not saving.

Thanks





Sudbury Arts Council / Sudbury Maandaa-Dnakmigziwin Teg / Conseil des Arts
de Sudbury <http://www.sudburyartscouncil.ca>


*If you no longer wish to receive email updates from the Sudbury Arts
Council, please respond with the word UNSUBSCRIBE and you will be removed
from our list. *
