### ISSUE TITLE
Video playing, redirect to a page or url, 0 as an answer doesn't work

### ISSUE THREAD

**Issue by tolgakutlu** [awsmug/torro-forms#421]
Hello Guys,
I have 4 problems with the plugin.  My website: https://www.dutchyipsstudy.nl/start-dys/

1:
Video playing doens't work below question 7 I choose as element type content an put the next text inside in it <p>Wat zijn de Yips ? 
<video muted="" controls="controls" width="800">
<source src="" type="video/mp4" />
Your browser does not support the video tag.
</video></p>

2:
When I choose one choice element and I choose required no the system says you must select a valid value from the list when i fill in the survey. How can I fix this that it is possible to don’t choose a answer? The Question below 24 is an example from what I mean.

3:
From one choice and dropdown element I have questions where an answers can be 0 the system doesn’t accept this. Question 15, 16, 17 is an example from what I mean. 

4:
Redirect doesn’t work to a page or url.

**Comment by mahype** [comment]
Thank you for reporting! :) We have been on a WordCamp the last days and will take a look at this.

**Comment by felixarntz** [comment]
@tolgakutlu Please open individual tickets for the four issues and follow the guidelines for posting an issue. We need precise information to replicate the behavior you're encountering.

**Comment by tolgakutlu** [comment]
@felixarntz I will do that
