### ISSUE TITLE
redirect to a page or url

### ISSUE THREAD

**Issue by tolgakutlu** [awsmug/torro-forms#428]
I add inside the Redirection an url but when someone submit the survey It doens;t redirect to the url. I tried also a redirect to a page the same problem. I see the success mesage when I submit the enquete but that is evertyting. My torro plugin version 1.0.0-beta.10 and wordpress version 4.9.5

**Comment by mahype** [comment]
Thank you for reporting! 👍  We will check that!

**Comment by felixarntz** [comment]
I cannot replicate this behavior. It works correctly for me, with both pages and URLs. Can you try without any other plugins? Is the URL you're redirecting to correct?

**Comment by mahype** [comment]
@tolgakutlu Does this problem still exists in the actual version? If not, we would like to close the ticket. ;)

**Comment by tolgakutlu** [comment]
@mahype you can close it.
