### ISSUE TITLE
No checkboxes values in email

### ISSUE THREAD

**Issue by Horttcore** [awsmug/torro-forms#432]
## Issue Overview
Using the `{value_element_5}` placeholder for a checkbox (multiple options) value in an email is empty

## Steps to Reproduce (for bugs)
* Create a form with checkbox and multiple options
* Add send form action
* Use the value placeholder
* Check the mail

## Expected Behavior
* Value 1
* Value 2

## Current Behavior
It's just blank 

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by mahype** [comment]
Thank you! I think this should be solved by Ticket #425. What do you think @felixarntz?

**Comment by felixarntz** [comment]
This was indeed fixed by #425.
