### ISSUE TITLE
An submodule with the slug email_notifications does not exist

### ISSUE THREAD

**Issue by eic** [awsmug/torro-forms#438]
In my plugin I try to add some Template_Tag_Handler to email_notifications submodule.
In the `instantiate_services` method I try to acces the email_notifications module with 

`$this->parent_plugin->modules()->actions()->get( 'email_notifications' );`

But get an error: An submodule with the slug email_notifications does not exist.

What I am doing wrong?
(Is there an alternative way or is there some code example)

**Comment by felixarntz** [comment]
Submodules are initialized on the `init` hook with priority 100 (see https://github.com/awsmug/torro-forms/blob/master/src/modules/actions/module.php#L117). So you need to hook in your method at a later point if you want to access the submodule.
