### ISSUE TITLE
Dropdown and one choice element answer equal to 0 not caching (saving)

### ISSUE THREAD

**Issue by tolgakutlu** [awsmug/torro-forms#440]
On my website https://www.dutchyipsstudy.nl/start-dys/ I have 2 one choose elements (questions 13 and 14) and 3 dropdown elements (questions 15, 16 and 17) where you can choose as an answer 0. If I choose 0 and sent the form the system you forget a required quiestion the system show the question(s) that you forget but the answers equal to 0 on questions 13 till 17 will also be empty.

**Comment by mahype** [comment]
Hi,

Thank you for reporting! :) 👍 I will check that!

Sven

**Comment by mahype** [comment]
Can you please recheck that with the 1.0.1 dev version? I have made a fix for problens on zero values:

https://github.com/awsmug/torro-forms/archive/1.0.1.zip

Thank you! :)
