### ISSUE TITLE
One choice element answer too long?

### ISSUE THREAD

**Issue by tolgakutlu** [awsmug/torro-forms#441]
On the last question the question after question 24 I have a problem. When you choose answer B. Kans maken .... and I sent the system says You must select a valid value from the list. It is the longest answer on the question that gives the problem
![afbeelding](https://user-images.githubusercontent.com/39030327/41747819-9cd51db6-75af-11e8-978b-93abac86604d.png)

**Comment by mahype** [comment]
Hi,

Thank you for reporting! :) 👍 I will check that!

Sven

**Comment by mahype** [comment]
Do you have any URL where I can check that in the source code?

**Comment by tolgakutlu** [comment]
Dear @mahype I look at the question there was space on the end that was the problem I think? The problem doenst occur anymore
