### ISSUE TITLE
Upgrade to 1.0.0 can't upload new element

### ISSUE THREAD

**Issue by tolgakutlu** [awsmug/torro-forms#443]
Today I upgrade to 1.0.0 I can add an element but If i update the page it doesn't show the element. Also when I change a element value. When I create a new form there is no problem it is only on the form what i created on 1.0.0 rc1. and earlier. I downgraded back to 1.0.0 rc1 but it didn't help to solve the problem.

**Comment by tolgakutlu** [comment]
I find the problem I have 2 dropdown element where you can selecht between 110 different answers. When I deleted this elements and add it again that the problem was solved but I think when I upgrade the plugin the problem will comeback

**Comment by mahype** [comment]
Sorry, but I did not get the problem... I have tried to reproduce by creating a form in RC1 and updated afterwards and added more elements. There was no problem with it. Maybe you have a caching problem or we need a more precise description in what you did. ;)

Thank you!

**Comment by tolgakutlu** [comment]
Okey maybe it is a caching problem. After the upgrade from rc1 to 1.0.0 the answers of the drop down questions became double. I have 5 drop down elements.
first drop down you can select an answers between 0 and 10 became 0 - 10 but then double answers (0, 0, 1, 1, 2, 2 etc etc)
second drop down you can select an answers between 0 and 10 became 0 - 10 but then double answers
third drop down you can select an answers between 0 and 10 became 0 - 10 but then double answers
fourth drop down you can select a answers between 1900 and 2018 became 1900 - 2018 but then double answers
fifth drop down you can select an answers between 1900 and 2018 became 1900 - 2018 but then double answers

totaly
