### ISSUE TITLE
backend form dropdown and one choice element value 0 problems

### ISSUE THREAD

**Issue by tolgakutlu** [awsmug/torro-forms#444]
From the backend if I want to edit a submission I got a problem when a dropdown or and one choice element have a value equal to 0. My torro version is 1.0.0
![afbeelding](https://user-images.githubusercontent.com/39030327/41803271-6178b2c2-7687-11e8-9836-fc1f6a24c58c.png)
![afbeelding](https://user-images.githubusercontent.com/39030327/41803287-825e36b0-7687-11e8-9f02-a3ad76a2fe3a.png)
![afbeelding](https://user-images.githubusercontent.com/39030327/41803280-706c0202-7687-11e8-9707-3a3813a5d768.png)

**Comment by mahype** [comment]
I am sorry, but I can not reproduce that, what I need to fix the bug. With which version do you have created the form? Also with 1.0.0?

**Comment by mahype** [comment]
Oh I got it! I have not been in the backend! We will work on that bug.

**Comment by felixarntz** [comment]
Fixed via https://github.com/felixarntz/plugin-lib/commit/2f13b2d5e0309b0e3adcf1057584ebe29e5c89cb
