### ISSUE TITLE
Action failures should not cause fatal errors

### ISSUE THREAD

**Issue by felixarntz** [awsmug/torro-forms#454]
As reported via DM by @kraftner, when a `WP_Error` is returned by the `handle()` method of an action, it causes a fatal error. That should not be the case, instead the error should simply be logged.

**Comment by kraftner** [comment]
Sorry for DM spamming and not making this an issue from the beginning :wink: 

Some more context:

If `handle()` returns a `WP_Error` it triggers the logger with an error:

https://github.com/awsmug/torro-forms/blob/c74d05f640d82f68a1adb8a792d39f6d0cecb2f5/src/modules/actions/module.php#L68-L75

This then maps to a `E_USER_ERROR`
https://github.com/awsmug/torro-forms/blob/d76adf747a1b2a457e1ea34d63c94dc17e89ebd3/src/logger.php#L44

hence triggering a `Fatal error` here
https://github.com/awsmug/torro-forms/blob/d76adf747a1b2a457e1ea34d63c94dc17e89ebd3/src/logger.php#L68

----

So I'd say either

1. in `Module::handle()` it should be `$this->manager()->logger()->warning()`or `notice()`
2. or you generally configure the Logger to map errors down to a warning to never trigger.

I guess 2. makes more sense though.
