### ISSUE TITLE
Evaluates participation submission count value differed from completed forms value

### ISSUE THREAD

**Issue by tolgakutlu** [awsmug/torro-forms#455]
Hello Guys. If I look at the backend submissions -> participation submission count I see there the value 189 but when I look at completed or all forms I see 150 as a value how can this be possible? Mustn't the submission count als be 150? I think the database contains deleted forms is it possible to see this in the database?
![afbeelding](https://user-images.githubusercontent.com/39030327/42539626-f6c5c884-849b-11e8-9827-25ef8c936ada.png)

**Comment by tolgakutlu** [comment]
@mahype do you now when you have time to check it?

Kind regards,

Tolga Kutlu

**Comment by mahype** [comment]
Hi Tolga!

I have checked this, but I could not personally reproduce exact the same issue but I had a similar.

I have all of my submissions if I am in a submission view of a specific Form. The numbers are inconsistent and we will fix that. I will label that as a bug and we will check in which version the fix will come.

Thank you for reporting! 👍 

Sven

**Comment by tolgakutlu** [comment]
Hi Sven,

Have you find a solution for this problem? If you want I can give you access to my website so that you can check the problem. I'm still waiting for a solution.

**Comment by tolgakutlu** [comment]
Does someone know when a solution will come for this bug?

**Comment by mahype** [comment]
Hi Tolga!

We could not reproduce this error until now. If you have a way how we could reproduce that, we could fix that. I will talk do my developer if he has new ideas where this comes from and will come back to you. 

Greetings,

Sven

**Comment by tolgakutlu** [comment]
Hi Sven,

I don't how to reproduce but what I wrote on 23-09-2018 you can check on my website. I can give you a account with permissions to test it and look at the log files if you can see anything. Or you can chck the database where the form data is written where the problems comes from. Downstairs you can read what I wrote on 23-09:

When I fill in the form from the frontend and I submit it I see when the form is completely filled in that the submissions count increase, but if the status of the form is in progress and I change the form from the backend and make the status completed the submissions count don't increase. When I delete a form the submission count don't decrease. I think in the element responses there are old data inside from deleted forms and or form results misses from forms that are changed in the backend. That is the reason that there are different value in completed forms and submission count.

King regards,

Tolga

**Comment by mahype** [comment]
OK. I have tested it now again but I have to check it on your site. I can't get it on my installations if I complete it in the backend and also if I delete a submission. Sorry for that. Can you send me some credentials, that I can try to reproduce it on your site?

I need WordPress and FTP credentials, can you send it by email to sven [ at ] awesome [ dot ] ug?

Then I will take a look!

**Comment by tolgakutlu** [comment]
Hi Sven,

I send your credentials (Wordpress + FTP) to your mail address.

Kind Regards,

Tolga

**Comment by tolgakutlu** [comment]
Hi @mahype have you tested or received my mail from 18-11-2018.

Kind Regards,

Tolga
