### ISSUE TITLE
Access Control: Session not started

### ISSUE THREAD

**Issue by kraftner** [awsmug/torro-forms#463]
## Issue Overview
Currently session-based access control is not working as in some situations the session is not initialized before the check. Therefore after successfully submitting a form you get a form access error instead of a confirmation message.
This at least happens when submitting a shortcode-embedded form with no redirection set.

## Steps to Reproduce (for bugs)

1. Enable "Access Controls" in Settings.
2. Enable "Access Controls/User Identification/User per submission ".
3. Set "Actions/Redirection/Redirect Type => No Redirection".
4. Embed the form via shortcode.
5. Submit form.

## Expected Behavior

You can access your own submission and get a confirmation message after submittal.

## Current Behavior

You can't access your own submission and get an error message after submittal.

## Possible Solution

The session is initialized only when you are on a form singular page or you just POSTed a submission here:
https://github.com/awsmug/torro-forms/blob/178c26ee1c8f16af1991ed2885b9374434afa9e9/src/db-objects/forms/form-manager.php#L407-L411
What I hackishly tried is just calling `session_start()` in any case which made the error go away.

So maybe just adding a check for `isset( $_GET['torro_submission_id'] )` should already do the trick, but I do not feel confident enough with the codebase to say if that actually fixes the root issue here.

The check that actually always fails due to a non-initialized session is here:
https://github.com/awsmug/torro-forms/blob/178c26ee1c8f16af1991ed2885b9374434afa9e9/src/modules/access-controls/user-identification.php#L83
So maybe always initializing the session here would also make sense.

---

As a temporary workaround enabling anything in "Access Controls/User Identification/Identification Modes/" fixes this for now.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by mahype** [comment]
Thank you for reporting the bug! 👍

**Comment by felixarntz** [comment]
@kraftner Let me know if the fix works for you. I made sure the currently queried posts are checked against shortcodes included. For those sites that consider this logic to be too expensive, an extra `torro_form_pre_start_session` filter is introduced that allows to include custom logic and short-circuit the original one.

**Comment by kraftner** [comment]
Sorry for taking so long to check.

So for my use case the filter somehow makes it work, but it is a bit tedious. I have two different use cases:

### Form in Template
The form is loaded in the template with a Form/Post ID from an option. Something like
`echo do_shortcode( '[torro_form id="' . esc_attr( $form['id'] ) . '"]' );`
So your logic never catches that.

### "Nested" Shortcodes
I have a custom  shortcode that then loads a form with some additional wrapping markup around it. (A shortcode triggering a tab-like navigation switching between two forms, but that's not really relevant for the issue)
Again this results in your logic not triggering as there is no torro forms shortcode in post_content.

-----

Thanks to the filter I can run my own logic which somehow makes it work, but as already said it is a bit tedious.
Not sure if my admittedly edge case usage is something you want to worry about though. :wink:
