### ISSUE TITLE
Add element context to CSS classes filters

### ISSUE THREAD

**Issue by kraftner** [awsmug/torro-forms#464]
## Issue Overview

There are plenty of filters for changing the classes of e.g. inputs and labels, but a lot of them lack context. E.g. right now I see no way to easily change classes depending on element type or even specific elements or forms.

## Expected Behavior
Add context to filters likes those in the [`Element` class](https://github.com/awsmug/torro-forms/blob/178c26ee1c8f16af1991ed2885b9374434afa9e9/src/db-objects/elements/element.php#L189-L232).

## Possible Solution

Add context similar to [what is done for the form](https://github.com/awsmug/torro-forms/blob/178c26ee1c8f16af1991ed2885b9374434afa9e9/src/db-objects/forms/form.php#L265).

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by mahype** [comment]
Good idea! :) If you have proposals for context filters just send it here. I will talk about that with @felixarntz
