### ISSUE TITLE
Feature request: Quizz protector

### ISSUE THREAD

**Issue by 17magic** [awsmug/torro-forms#469]
Hi!

Could you kindly add the typical quizz protector like

Question => answer

Answer need to accept letters and numbers :)

I need to ask something unique to my users and seems to be the easiest way to reach this goal :)

If answer is good the submit will be done

Thanks in advance 
Cheers

**Comment by mahype** [comment]
Hi,

I am sorry, but I do not really know what you are meaning. Can you please help me with some details about what a quizz protector is exactly doing. Maybe do you have an example for that?

Thank you!

Sven

**Comment by websupporter** [comment]
> If answer is good the submit will be doneI think its something like "Are you a human, solve this quiz: What is 1+3"

**Comment by mahype** [comment]
Ahh OK! Thank you! :) I will take a look at it. Maybe there is a way we can implement something like "correct answers". But maybe this is something for an extra plugin.

**Comment by 17magic** [comment]
Exactly websupporter ;)

but not only math problem ...
I wish to ask something like :
(e.g) What is the US President name : 
in fact I need to configure the question AND the answer ;)
Hope you can find a way to add this feature asap :)
Thanks in advance

**Comment by mahype** [comment]
I will create a plugin which will collect some additional protectors for Torro Forms and link that when I have created the first repository with the first code that you can follow the development there.

**Comment by 17magic** [comment]
Hi! :)

Any news ? :)
Of course the good answer do not be visible in the source code of the page!

Can't wait to test your solution!
Cheers
Phil

**Comment by mahype** [comment]
Yes there are news

I created a first pre-version of a plugin, where we can collect protectors:

https://github.com/awsmug/torro-forms-protectors-plus/releases/tag/0.1.0

I have added a mathematics protector as first plus protector ;) You can try it now!

**Comment by mahype** [comment]
For further actions see https://github.com/awsmug/torro-forms-protectors-plus/
