### ISSUE TITLE
"Next Step"-Button does not forward to next page.

### ISSUE THREAD

**Issue by mkronenfeld** [awsmug/torro-forms#475]
## Issue Overview

Pressing the "Next Step"-Button redirects the user to the home page instead of the step 2 page.

## Steps to Reproduce (for bugs)

1. Create a multi-page form.
2. Page 1, Text field: Foo, required.
3. Page 2, Text field: Foo, required.
4. Publish and access the form (direct or shortcode).
5. Fill out the foo field.
6. Press the "Next Step"-Button.

* PHP-Version 7.0.28
* WordPress 4.9.8
* Active Theme:
  * Twenty Seventeen 1.7
  * Just a bit custom CSS in the customizer.
* Active Plugins:
  * Torro Forms 1.0.3
  * Gutenberg 4.4.0

## Expected Behavior

I am expecting to be redirected to page 2.

## Current Behavior

I was redirected to the home page.

## Possible Solution

n/a

## Screenshots / Video

n/a

## Related Issues and/or PRs

n/a

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by mahype** [comment]
Perfect! Thank you! 👍

**Comment by mahype** [comment]
I tried to reproduce the error but for me it is working. I checked the code and the POST URL which was wrong in your form ist produced by this line:

https://github.com/awsmug/torro-forms/blob/master/src/src/db-objects/forms/form.php#L284

I read that the filter functions we use, made problems in other scripts. Maybe you could test this code:

`add_filter( 'torro_form_action_url', function() {
   return $_SERVER['REQUEST_URI'];
});`

Can you check this out and give mee feedback?

**Comment by mahype** [comment]
https://github.com/xwp/stream/pull/263/commits/871ae5380a990996a75aff8cb77283cca225d917

**Comment by mahype** [comment]
OK. I will create a fix for that and will bring it to the next Torro Version. As you can see in the WordPress Ticket, you are not alone ;)

**Comment by mahype** [comment]
Ahhh I found something. Seems to be a very old but never fixed PHP bug:

"filter_input() doesn't work with INPUT_SERVER or INPUT_ENV when you use FASTCGI".

https://stackoverflow.com/questions/25232975/php-filter-inputinput-server-request-method-returns-null

**Comment by mahype** [comment]
This should be catched by the latest commits @mkronenfeld. Thanks for helping! 👍
