### ISSUE TITLE
Feature Request: API Endpoint for Form Submissions.

### ISSUE THREAD

**Issue by askilondz** [awsmug/torro-forms#479]
This is a feature request to add an API endpoint for submitting to the form from an external (non-wordpress) site or mobile app. Providing an endpoint like `mywordpresssite.com/torro/v1/submit` for all users that allows us to submit from external applications and be able to view the submissions in wordpress is a feature I have yet to find across all contact form plugins available on wordpress. Would love to finally see this in a form plugin.

**Comment by mahype** [comment]
Hi,

there are endpoints. Just take a look to the /wp-json url after you have logged in to your WordPress:

![bildschirmfoto 2019-01-19 um 14 41 20](https://user-images.githubusercontent.com/663697/51427445-54cbea00-1bf8-11e9-9414-893e187dbece.png)

Greetings,

Sven
