### ISSUE TITLE
Element bootstrapping settings with formfield type="datetime" causes notices

### ISSUE THREAD

**Issue by sebuchy1991** [awsmug/torro-forms#481]
## Issue Overview
Extending element settings on Formbuilder with a datetime fieldtype, causes a notice.

## Steps to Reproduce (for bugs)
1. Install a plain version of your element boilerplate
2. Extend the date-elements bootstrap() method with the following code :

`$this->settings_fields['test_setting'] = array(
	'section'    => 'settings',
	'type'       => 'datetime',
	'store'      => 'date',
	'label'      => __( 'Date field test.', 'cmwp-torro-elements' ),
	'default'    => '',
);`

3. It causes the following notice ( Don't forget to set WP_DEBUG = TRUE; on wp-config.php ):

Notice: Undefined index: store in /var/www/html/wp-content/plugins/torro-forms/vendor/felixarntz/plugin-lib/src/fields/datetime.php on line 96

4. But anyhow it does its job. When i change "store" from date to time it also changes it on frontend functionality. Hmmm did i miss something? 🤓

**Comment by mahype** [comment]
Hi Sebastian,

thank you for that hint. I will take a look at this!

:)

**Comment by mahype** [comment]
Isn't this solved by your a pull request now?

**Comment by sebuchy1991** [comment]
No the pull requests just added some hooks

**Comment by mahype** [comment]
Aah OK! Thank you! :)
