### ISSUE TITLE
Phone text-fields not shown on submission-edit page

### ISSUE THREAD

**Issue by sebuchy1991** [awsmug/torro-forms#491]
## Issue Overview
After getting some submissions from a form, using phone textfields, we found out that these fields are not visible at submission-edit-page.

## Possible Solution
I checked out the way the fields are getting rendered and i checked out that the field_type isn't supported by vendor/felixarntz/pluginlib.

You can watch this at the method "register_default_field_types" at file: /vendor/felixarntz/plugin-lib/src/fields/field-manager.php::990

It needs to get an array part like:
'tel' => Tel::class

But you also need to add a "Tel" class.
It is actually not implemented ( /vendor/felixarntz/plugin-lib/src/fields/ )

I hope there is a way to implement this at the new version :)

**Comment by mahype** [comment]
Hi Sebastian,

I have totally missed your ticket here. Sorry for that! I have changed the plugin libt to awsmug/plugin-lib:dev-master. Now you can do pull requests on the library also.

Greetings,

Sven

**Comment by mahype** [comment]
Hi Sebastian, 

there is also function which allows you to implement your own field types in the plugin lib. Take a ook here:

https://github.com/awsmug/plugin-lib/blob/master/src/fields/field-manager.php#L912

Maybe that helps you!

Greetings,

Sven
