### ISSUE TITLE
custom frontend button style

### ISSUE THREAD

**Issue by alexlii1971** [awsmug/torro-forms#493]
Hello,

Maybe I missed something, is there a way to custom the button frontend style please?

Thanks

**Comment by alexlii1971** [comment]
Alternatively, how to use the theme style please?

**Comment by mahype** [comment]
Hi Alex,

no there isn't a way to do it in the backend, you have to use CSS. 

For that you can put in your CSS the the classses:
`
.torro-pager .prev > button {
  /** Your CSS Code here **/
}
.torro-pager .next > button {
  /** Your CSS Code here **/
}
`

Greetings,

Sven
