### ISSUE TITLE
How to enable shortcode from other plugin to work in forms?

### ISSUE THREAD

**Issue by alexlii1971** [awsmug/torro-forms#494]
Hello,

Most of shortcodes from other plugins works well in forms.

I am using Smart coupon which is a Woocommerce official plugin at https://woocommerce.com/products/smart-coupons/

And I input shortcode like this way:

http://prntscr.com/n6ht6a

and it will show this way at frontend:

http://prntscr.com/n6httx

would you please let me know how to enable shortcodes in Forms?

Thanks

**Comment by mahype** [comment]
Hi Alex,

sorry for the late answer but shortcodes are working for the content element. I think the shortcode is wrong. The shortcode has no setting that it can begin with an "=" direct aftert the short code name. I think this should be the problem.

Greetings,

Sven
