### ISSUE TITLE
PHP notice when submitting a form with required multi-choice checkbox field

### ISSUE THREAD

**Issue by florianbrinkmann** [awsmug/torro-forms#495]
## Issue Overview

I created a form with various fields (normal text, single checkbox, multi checkbox, radio and select) and get the following notice three times after submitting it without entering any values:

```
( ! ) Notice: Array to string conversion in C:\xampp\htdocs\example.com\wp-content\plugins\torro-forms\vendor\felixarntz\plugin-lib\src\db-objects\model.php on line 546
```

I have three multi-checkbox fields in the form, so I tried what happens when I tick a checkbox for all of them: the error disappears.

## Steps to Reproduce (for bugs)

1. Create a form with multi-checkbox field that is required
2. Insert it into a page.
3. Submit it without ticking a checkbox.

I am using PHP 7.2.6 and WordPress 5.1.1 with XAMPP on a Windows 10 machine.

**Comment by mahype** [comment]
Hi @florianbrinkmann ,

I am sorry, but I can reproduce that. Can you please check if it works now? Maybe it is gone with the latest verson.

Greetings,

Sven

**Comment by florianbrinkmann** [comment]
Hi @mahype,

yes, I cannot reproduce the error either, seems to be gone. But: Now I get the following notice multiple times (seems to come for each field in the form):

```
( ! ) Notice: compact(): Undefined variable: limits in path\wp-content\plugins\torro-forms\vendor\felixarntz\plugin-lib\src\db-objects\query.php on line 505
```

Best,
Florian

**Comment by mahype** [comment]
Thank you for this infomation! :)  This is covered by by a fix in the next plugin lib update. 

https://github.com/felixarntz/plugin-lib/issues/6
