### ISSUE TITLE
Fails to activate in WP 5.1.1

### ISSUE THREAD

**Issue by ScreamingDev** [awsmug/torro-forms#497]
## Issue Overview

On a (almost) clean WordPress I want to install Torro Forms.
During activation it fails with this message

> The plugin does not have a valid header.

## Steps to Reproduce (for bugs)

1. PHP 7.1 + WP 5.1.1
2. Use backend to download
3. Use backend to activate.
4. Error message appears.

## Expected Behavior

I cheer, dance and start to create forms.

## Current Behavior

Error-Log during activation

```
PHP Notice:  register_uninstall_hook was called <strong>incorrectly</strong>. Only a static class method or function can be used in an uninstall hook. Please see <a href="https://codex.wordpress.org/Debugging_in_WordPress">Debugging in WordPress</a> for more information. (This message was added in version 3.1.0.) in wp-includes/functions.php on line 4667
[27-May-2019 14:46:58 UTC] PHP Notice:  get_currentuserinfo is <strong>deprecated</strong> since version 4.5.0! Use wp_get_current_user() instead. in wp-includes/functions.php on line 4329
```

## Possible Solution

Those are just notifications, so ... dunno.

## Screenshots / Video

![image](https://user-images.githubusercontent.com/2559177/58427257-638f4580-809f-11e9-8a8a-0a66392534aa.png)

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by mahype** [comment]
Hi @ScreamingDev! 

Thanks for reporting.

I can not reproduce this error. I have set up an the PHP 7.1.4 environment with WP 5.1.1, set the WP_DEBUG to true and also switched on the PHP error_reporting to E_STRICT. Also I habe checked for the errors. Torro forms is using a static function for the uninstall hook. Also there is no use of the function get_currentuserinfo. We already use the function wp_get_current_user() as recommended above.

Do you have tried to switch off other plugins of the installation and tried to switch it on again?
