### ISSUE TITLE
Update plugin-lib

### ISSUE THREAD

**Issue by kraftner** [awsmug/torro-forms#498]
## Steps to Reproduce (for bugs)

The currently used version of plugin-lib [throws notices with PHP 7.3](https://github.com/felixarntz/plugin-lib/issues/6) that make Torro Forms pretty much unusable in a dev environment.

## Expected Behavior

No Notices. :smile: 

## Current Behavior

Notices. :cry: 

## Possible Solution

Update plugin-lib to include the fix from https://github.com/awsmug/plugin-lib/commit/3a1ee039beb4ffe3fe54bc968b354260c5f11b95.

## Related Issues and/or PRs
https://github.com/felixarntz/plugin-lib/issues/6

**Comment by mahype** [comment]
This is solved by the last commit in the master branch. I have updated the plugin lib and torro forms.
