### ISSUE TITLE
Form submit and validation not working

### ISSUE THREAD

**Issue by gwyn** [awsmug/torro-forms#499]
I can not get the plugin to work correctly and noticed several problems along the way. Maybe some of those are responsible, but I just can't figure it out.

I am using WordPress 5.2.2.

At first, I installed Torro Forms 1.0.5 through WordPress Plugin Search. Clicking on "Install now" the plugin installs fine, but if I press "Activate", it fails with the error message "The plugin does not have a valid header." However, when I go back to the installed plugin list and click "Activate" there, it becomes activate.

Then I was able to configure everything, edit the plugin settings as well as create and publish a form. So I didn't think much about it.

But when a user presses the form's "Submit" button, they are redirected to the static main page and no entries are being made. Also, I do not receive the email notice I configured. The page redirect action to a page of my chosing does not work either.

If required fields are left blank, there is no validation on submit. The user is simply being redirected to the static main page. Shouldn't the form redraw or at least show hints?

Looking closer at the form submit, I see a HTTP POST to the WordPress base URL with torro_submission[] form data:

```
torro_submission[values][11][_main]: 
torro_submission[values][12][_main]: 
torro_submission[values][13][_main]: 
torro_submission[values][15][_main]: 
torro_submission[action]: submit
torro_submission[nonce]: e78785a45c
torro_submission[form_id]: 28
```

I can see these HTTP requests (my WordPress base URL contains a path):
1. HTTP POST https://my.domain.com/mypath
   301 Redirect to https://my.domain.com/mypath/
1. HTTP GET https://my.domain.com/mypath/

Is that intended behaviour? Could it be that the WordPress hook to capture the torro_submission does not fire the plugin logic correctly?

Then I remembered the installation problem and tried to install the latest torro-forms-master ZIP from Github as explained in the tutorial video here:
https://torro-forms.com/user-guide/getting-started/

It fails to install right away, as WordPress does not see it as a valid plugin.

Details about my setup:
* WordPress 5.2.2
* Torro Forms 1.0.5
* PHP 7.1.15
* Browsers tested:
  * Chrome 75.0.3770.100
  * Firefox Quantum 67.0.1

**Comment by mahype** [comment]
Hi @gwyn,

thank you for your detailed report! I will check this. Do you have installed any further plugins?

Greetings,

Svenn

**Comment by mahype** [comment]
OK. This could also adress the issue #475 which should be solved now. Can you download the actual code from the master branch and replace the plugin by the code from the /src directory and give me feedback?

Download from here:
https://github.com/awsmug/torro-forms

**Comment by gwyn** [comment]
Thanks, I created a ZIP file from the master branch src directory and uploaded it to WordPress. It installs fine and I can activate it.

Unfortunately, the "Submit" still redirects to the static main page.

I do not have any other plugins in the WordPress installation, Torro Forms is the only one. I use the Twenty Nineteen theme. It was a fresh install to test out Torro Forms.

However, I did some tweaking with the theme and fiddling with other 3rd party plugins before, but removed them again. I also noticed another problem with Torro Forms along the way. When changing the forms slug after a form was created, the displayed permalinks didn't work anymore. I eventually found out this can be fixed by going to WordPress permalinks settings and just saving them (without changing anything there).

Anyway, to be absolutely sure I have now installed an additional completely vanilla WordPress 5.2.2 de_DE test instance. No configuration changes whatsoever from the defaults. I added the Torro Forms plugin from master branch src ZIP and created a simple example form with one external URL redirect action.

I can reproduce the same behaviour: The form submit and validation is not working and the actions are not executed. I get redirected to the main page.

Please let me know if I can further help you narrow down the problem.

**Comment by mahype** [comment]
Can you send me an email with the credentials to the vanilla installed site to support (at) awesome (dot) ug? I think I have to see it in detail.

**Comment by gwyn** [comment]
Thank you, I've sent you the details via email.

In the meantime I've also tried to reproduce the problem using a WordPress docker image, but to no avail. So it might be a problem specific to my webspace hosting environment. One thing I noticed is that the HTML form action URL is actually the WordPress base URL. In the docker environment it is the form's URL.

**Comment by mahype** [comment]
Hi Gwyn,

this is fixed now by the commit mentioned above.

Greetings,

Sven

**Comment by gwyn** [comment]
Thank you, the latest release 1.0.7 works great!

I would recommend to handle the URL retrieval slightly different though. For pretty path permalinks it works fine, for plain ones with query parameters not so much. These parameters are missing in $wp->request.
