### ISSUE TITLE
add automation with gulpfile, dependency management with composer

### ISSUE THREAD

**Issue by felixarntz** [awsmug/torro-forms#58]
* [x] move CSS, JS and images to "assets"
* [x] figure out all dependencies and load them via composer (or bower for JS stuff)
* [x] compress stylesheets and scripts (maybe SASS for CSS?) using Gulp
* [x] load minified resources everywhere (if not SCRIPT_DEBUG)

**Comment by mahype** [comment]
Moving CSS, JS and images to "assets" and compile them with gulp.

**Comment by mahype** [comment]
3rd Party:

JS:
- C3
- D3

PHP
- PHPExcel

**Comment by felixarntz** [comment]
* when done, create a PHP class taking care of file inclusion, both for PHP and assets
