### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by felixarntz** [awsmug/torro-forms#64]
Global task for some refactoring / major code changes.

- [x] change textdomain when we have the plugin slug figured out (to `torro-forms`)
- [x] change class, function, action, filter prefixes from `AF_` to `Torro_` (`af_` to `torro_`)
- [x] choose a coding standard and stick with it (communication required, I'd propose to choose the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/))
- [x] find unused methods and remove them
- [x] reworking "components" / "component similar objects" by doing one parent Class for all
- [x] element properties have to be rethought/renamed

Extend this list as needed.

**Comment by felixarntz** [comment]
@mahype I really think we should stick to the WordPress Coding Standards. This will be a (really annoying, I have to admit) one-time work to adjust all the existing code. I could do that, would be fine with me. After that, we would only need to consider the rules when writing new code. I can also build-in an automatic code style validation with gulp to make sure we're consistent.

This whole change might seem irrelevant, but it will definitely benefit the whole project long-term, both for code-readability and for possible collaborators / pull requests.

See https://make.wordpress.org/core/handbook/best-practices/coding-standards/

So what do you think? Sounds good? :)

**Comment by mahype** [comment]
Yes this sounds good. I'll think we speak about this next week.
