### ISSUE TITLE
REST API Endpoints

### ISSUE THREAD

**Issue by felixarntz** [awsmug/torro-forms#76]
- allow people who create non-WP themes using the WP API to use their forms
- endpoints:
  - GET `forms/:id` (form data, most importantly field data, nonces etc)
  - GET `forms/:id/results` (form results data)
  - POST `forms/:id/results` (submit form, returns action data)

We should start working on this for a later version, shortly after 1.0.

**Comment by mahype** [comment]
Sounds good! :)

**Comment by felixarntz** [comment]
Done as part of refactoring.
