### ISSUE TITLE
Results

### ISSUE THREAD

**Issue by bueltge** [awsmug/torro-forms#8]
See the follow screenshots. Not all topics are visible.
The screenshot is from Chrome, Win 7.
In IE 10, Win7 is it not usable (But maybe is the IE not in focus).

![example](https://cloud.githubusercontent.com/assets/133425/8524734/49bdf1c2-23fd-11e5-8f2d-b0d7f118f01e.png)

**Comment by bueltge** [comment]
See the screenshot below after update to 1.0.0 beta 16, with chart.js

![example](https://cloud.githubusercontent.com/assets/133425/8524831/c5a8c780-23fd-11e5-86a6-70b77395a442.png)

**Comment by mahype** [comment]
Thats crap! :) Thank you for reporting! I've got to fin annother solution.

**Comment by bueltge** [comment]
Maybe additional css is enough?

**Comment by mahype** [comment]
Thats a very good idea! I switched back to D3 Dimple and I'm trying out now. I've added the changes to the branch beta17. Maybe you've got also an idea what CSS I have to change.

**Comment by bueltge** [comment]
OK, maybe I will help. After you implement this "old" solution ping me. But I'm offline from 20.7. to 20.8. -- Holiday :cake:

**Comment by mahype** [comment]
This didn't worked with CSS directly. I had to autosize the graphics with JavaScript. Can you please try out the beta17 branch?

**Comment by bueltge** [comment]
Much better ;)

![example](https://cloud.githubusercontent.com/assets/133425/8571338/69d79ece-2586-11e5-887b-9d4ae1eda690.png)

**Comment by bueltge** [comment]
Now I miss only values to:
 * How much participant?

**Comment by mahype** [comment]
Now I'm not resizing the whidh anymore, because it wasn't really needed. Can you check the width again?

I don't really understand what you meant whith the missing values. Can you explain it or is this also fixed now?

**Comment by mahype** [comment]
I also have added the result view to the admin an an additional metabox.

**Comment by bueltge** [comment]
Inside the meta box works fine, in the front end of the theme is it same as my screenshot. The values of the inline stylesheets is to small.

to my other topic. It is helpful, that we have on the entry of the result view a count of all participants, that is view able, how many users have get his answer to the question.

**Comment by bueltge** [comment]
attached a result, html. Maybe this helps you.
https://www.dropbox.com/s/bued79rkjkxlr27/example-result.zip?dl=0

**Comment by mahype** [comment]
I added some CSS which I couldn't test if this is the right for you. Just check this or maybe we can do a call tomorrow.

**Comment by bueltge** [comment]
Same problems after test of the last beta17 and his commit before 2mins.
Maybe a call tomorrow.

**Comment by mahype** [comment]
In the next version we have changed to C3. It's a JS Library based on D3. This can handle long Texts very well. We can talk next Week in Berlin about upgrading your installation from Questions to Awesome Forms if you want :)

**Comment by mahype** [comment]
Hallo Frank,

would it be possible to checkout an update from Questions to Torro forms with your surveys?

That would be great!

Sven

**Comment by bueltge** [comment]
Hi Sven. Yes, I will, but currently no time. Later and I give feedback here or directly. Best
